### ISSUE TITLE
Sticky list-filter, overlaying and floating left over the list contents in some mysterious circumstances

### ISSUE THREAD

**Issue by andrewhayes1979** [fabiocaccamo/django-admin-interface#100]
**Python version**
3.8.3

**Django version**
2.2.17

**Package version**
django-admin-interface==0.14.0

**Browser/system**
Chrome 86.0.4240.183 (Official Build) (x86_64)
Mac OS X Catalina 10.15.7

**Current behavior (bug description)**

I have a medium sized project, it has maybe 50 models and associated admins.

I recently updated to the latest version of admin interface, there's a "list filter sticky" flag been added.

This works fine on nearly all admins, however I have one admin in my project where the list filter hovers over the list view and floats left over the list content...only one!  If I disable the new sticky on the theme, everything is fine, **so the new sticky functionality appears to be to blame.**

I've tried extensively to find the problem, but can't.

I've reduced the complexity of the admin to reduce it to a single column containing the model ID and a single list-filter on a boolean field to make the list filter appear...pretty minimal. It still happens!

There's no template overriding on the go, no style overrides. As far as I'm aware, the template and styles are as your package provides them (there's nothing else overriding admin templates in any meaningful way).

It's very odd

<img width="1120" alt="Screenshot 2020-11-11 at 17 03 26" src="https://user-images.githubusercontent.com/784691/98842379-658ac700-2441-11eb-9334-5a9d7841652e.png">

...I can't find what the issue is, so can't give you a pull request.  Nor can I really provide a way to reproduce :-/

But be aware, there is an issue

**Expected behavior**

Filter should always sit on the right (in desktop window sizes), sticky or not...the mobile styles correctly kick in and move the filter below the list, so there's no issue there...it's just desktop.

**Comment by fabiocaccamo** [comment]
Have you installed any admin library/plugin or custom admin js? 
Could you check in the browser logs if there is something useful for debugging this?

**Comment by andrewhayes1979** [comment]
I've removed the meaningful data and gone back to the minimal admin (couple of columns, one-field filter)

It's reproduced here, I've saved out the web-page in full and zipped...that's all HTML, CSS and JS

The "Foundation" off-the-shelf theme is in use installed from your fixtures...don't think it's been changed from the defaults.

I do have a custom admin-app myself, but that's limited to providing utils and ModelAdmin mixins/filters/actions/utils etc.  Does a few things around inserting links in the header etc. but nothing major.  It used to be far more extensive override-wise, but now I mostly back onto your excellent package.

Find the example page attached:
[StickyFilterIssue.zip](https://github.com/fabiocaccamo/django-admin-interface/files/5525798/StickyFilterIssue.zip)

**Comment by fabiocaccamo** [comment]
@andrewhayes1979 thank you for reporting this issue and for providing the minimal example. I now understand the cause of the problem. 

The truth is that this feature is not very compatible with django versions < 3.1.2, because the admin DOM structure is changed a little bit.

You see the problem only on this model because there is not admin toolbar, just try to add `search_fields` in you model admin and the problem should be solved... let me know if I'm right, in that case I will release a *dirty* fix to avoid this unpleasant scenario.

**Comment by andrewhayes1979** [comment]
Hi

Yes, disabling the sticky flag is what I've done to fix the issue in the interim.

And yes, adding search_fields into the admin does make it behave (find another example attached)

[StickyFilterIssueWithSearch.zip](https://github.com/fabiocaccamo/django-admin-interface/files/5529370/StickyFilterIssueWithSearch.zip)

Thanks for the quick investigation!

**Comment by fabiocaccamo** [comment]
@andrewhayes1979 you can upgrade `django-admin-interface` to `0.14.1` version.
