### ISSUE TITLE
TabularInline  scroll bar

### ISSUE THREAD

**Issue by avanguardigit** [fabiocaccamo/django-admin-interface#101]
**Django version**
3.1

**Package version**
0.14.1

**Current behavior (bug description)**
there is an error in the management of "TabularInline". 
the scroll bar is permanently shown
the css class is:

.admin-interface .inline-related.tabular fieldset.module {
    display: block;
    overflow-x: scroll;
    width: 100%;
    white-space: nowrap;
    position: relative;
}

**Expected behavior**
I think you can solve with

.admin-interface .inline-related.tabular fieldset.module {
    display: contents;
    overflow-x: scroll;
    width: 100%;
    white-space: nowrap;
    position: relative;
}

**Comment by fabiocaccamo** [comment]
Could you add a screenshot of the problem please?

**Comment by avanguardigit** [comment]
![image](https://user-images.githubusercontent.com/33161350/100229581-c1b31800-2f24-11eb-8eb9-5e67fce8ac6c.png)
I found this problem with google crome 

If I use edge, this is the resault
![image](https://user-images.githubusercontent.com/33161350/100229756-05a61d00-2f25-11eb-921e-4fe507c1c3d1.png)
but the cursor it's block, I can't move left or right (if I have any data)

I think the "problem" it's with this pack, because If i disable it, all work correctly

**Comment by fabiocaccamo** [comment]
@avanguardigit you can upgrade to `0.14.2` version.
