### ISSUE TITLE
Change active page colors

### ISSUE THREAD

**Issue by ChrisCrossCrash** [fabiocaccamo/django-admin-interface#102]
**Python version**
3.8

**Django version**
3.1.3

**Package version**
0.14.1

![admin_interface_issue](https://user-images.githubusercontent.com/40023417/99507111-058da680-2994-11eb-8a0c-dbc01ab39f11.png)

I can't change the font color of the active app listed on the left hand side ('.module .current-app .section') and the background of the active model in that app ('.model-signup .current-model')

I'd like to be able to change these colors from the Theme page. Some color schemes simply won't work because the contrast will be too low with the default color.

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash you can upgrade to`0.14.2` version, the active color is not customizable but I fixed the module link color.

**Comment by ChrisCrossCrash** [comment]
That's great! Upgraded now. The active color isn't such a big deal. It was just kind of hard to read the yellow font against a lighter colored background.
