### ISSUE TITLE
You can't run "python manage.py collectstatic"

### ISSUE THREAD

**Issue by nilesh212** [fabiocaccamo/django-admin-interface#106]
I did follow your readme path for installing "django-admin-interface", but when I tried to run the command "python manage.py collectstatic" it asked me to create STATIC_ROOT.
So I was suggesting if you could add some more clarity to the command "python manage.py collectstatic".
I would really like to add something in the "Readme.md" file if you give permission, just to clarify why that "python manage.py collectstatic" won't work until you create STATIC_ROOT.

**Comment by fabiocaccamo** [comment]
@nilesh212 this is not related to this library, but to how `django` handles static files: 
https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-STATIC_ROOT

**Comment by nilesh212** [comment]
but, if you just give more clarity on why the ``` python manage.py collectstatic``` won't work, that would be better.

**Comment by merwok** [comment]
Fabio’s point is that this is a general Django thing, not something specific to this library, so this project can’t answer all Django questions in its readme.

**Comment by nilesh212** [comment]
I got that, thanks @merwok.
If you could tell me something about contributing to the open-source projects, that will be a great help for me.

**Comment by merwok** [comment]
Oh that is a big question!

I guess the general advice would be to choose a project that you use and enjoy, that’s not too small (one or two maintainers are often too busy and not always experienced in welcoming beginners) and not too big (could have too many things going on, too many rules, etc), and find something that’s interesting to fix or add.

**Comment by nilesh212** [comment]
Well, that was a pretty big question and you answered it. Thanks, @merwok.

**Comment by fabiocaccamo** [comment]
@nilesh212 "Necessity is the mother of invention", just put your hands on real projects, use existing libs to simplify the job, and all the rest will be more natural than expected.
