### ISSUE TITLE
Theme is not applied with  django-admin-index

### ISSUE THREAD

**Issue by mwolff44** [fabiocaccamo/django-admin-interface#108]
**Python version**
3.7

**Django version**
2.2

**Current behavior (bug description)**
Theme is not applied to horizontal menu using  django-admin-index

**Comment by fabiocaccamo** [comment]
@mwolff44 I never used `django-admin-index`, feel free to submit a PR adding styling for this library.

**Comment by fabiocaccamo** [comment]
@mwolff44 Third party applications can now be *optionally* styled according to `django-admin-interface` theme:
https://github.com/fabiocaccamo/django-admin-interface#add-theme-support-to-third-party-libraries

**Comment by mwolff44** [comment]
@fabiocaccamo thanks a lot !
