### ISSUE TITLE
Multiple fields on a single line doesn't look right on mobile view

### ISSUE THREAD

**Issue by sayeghr** [fabiocaccamo/django-admin-interface#109]
**Python version**
3.8

**Django version**
3.1.2

**Package version**
0.14.2

**Current behavior (bug description)**
When multiple fields are set to be displayed on the same line, the responsiveness looks good for all window sizes EXCEPT mobile.

i.e. 
`    
fieldsets = (
        (None, {
            'fields': (('name_en', 'name_fr'), ('description_en', 'description_fr'))
        }),
    )
`

**Expected behavior**
On mobile view, fields should switch to being displayed one per line. Currently on small view it is displayed one per line but then goes back to both being displayed on both being on a single line on a mobile screen size.

Big Screen:
![big-screen](https://user-images.githubusercontent.com/4521674/105055771-6a6f8680-5a41-11eb-9303-a616ecbe7634.png)

Small Screen:
![small-screen](https://user-images.githubusercontent.com/4521674/105055800-72c7c180-5a41-11eb-8f2f-81c63be0d1b8.png)

Mobile Screen:
![mobile-screen](https://user-images.githubusercontent.com/4521674/105055804-75c2b200-5a41-11eb-9fea-755a4c0c574c.png)

**Comment by fabiocaccamo** [comment]
Have you tried without this library?

**Comment by sayeghr** [comment]
@fabiocaccamo Just did. The same problem exists. So this is an issue in django-admin itself.

**Comment by fabiocaccamo** [comment]
@sayeghr thank you. Are you using `django-modeltranslation` ?

**Comment by sayeghr** [comment]
Yes I am.

**Comment by fabiocaccamo** [comment]
@sayeghr I suggest you to use the [tabbed model admin](https://django-modeltranslation.readthedocs.io/en/latest/admin.html), it is nicely styled by this library :wink:
