### ISSUE TITLE
Request for support 4-digit language code

### ISSUE THREAD

**Issue by cpcpaicp** [fabiocaccamo/django-admin-interface#111]
Thank you very much for your excellent work. Since Django replace zh-cn, zh-tw, zh-sg to zh-hans and zh-hant, more and more programmers have also begun to use these new language codes, but I found admin_interfaces have no support yet. 
So, urls like '/zh-hans/admin/' are recognized as admin_nolang_url, which causes the language switcher not displayed.
It would be great if this feature could be added, thanks.

**Comment by fabiocaccamo** [comment]
@cpcpaicp thank you for reporting this, it will be fixed soon.

**Comment by fabiocaccamo** [comment]
@cpcpaicp you can upgrade to the latest version.
