### ISSUE TITLE
Sticky submit row should use 100% width

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#113]
**Python version**
irrelevant

**Django version**
3.1.6

**Package version**
0.15.2

**Current behavior (bug description)**
In an admin edit page with no sidebar + sticky submit row, there’s empty space on the left:
![djadint-width-bug](https://user-images.githubusercontent.com/635179/107161895-b2613980-696d-11eb-98cd-17f339043e4c.png)

**Expected behavior**
The row should use the full width of its container.

**Comment by theSinner** [comment]
Hi @merwok 

I think this bug is related to Django itself. Because the main tag should not have the `shifted` class in this situation.
I sent a [pull request](https://github.com/django/django/pull/13986) to the Django project
