### ISSUE TITLE
error with version >0.15 

### ISSUE THREAD

**Issue by avanguardigit** [fabiocaccamo/django-admin-interface#114]
**Python version**
3.7

**Django version**
3.1.3

**Package version**
>15

I have try to update to 0.15.3 but this version give me some problem.

ERRORE: la colonna admin_interface_theme.form_submit_sticky non esiste 
LINE 1: ..."admin_interface_theme"."recent_actions_visible", "admin_int... ^

I have try 0.15.0 , 0.15.1, 0.15.2 with the same resault, with the versione 0.14.2 all work correctly.

**Comment by fabiocaccamo** [comment]
You must just run `python manage.py migrate admin_interface`.
