### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by saymoncoppi** [fabiocaccamo/django-admin-interface#115]
# Hello @fabiocaccamo! 
Tks for your great work on this project.

I realized that maybe I got an issue with the translations.
Could you take a look at that or gimme instructions to fix it?

Even if the "language_chooser" is enabled I couldn't see the options to change the language.

The translations are working since I've already edited files:

## settings.py

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    ...
]

LANGUAGES = (
    ('en', 'English'),
    ('pt-br', 'Português'),
)

## urls.py
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    prefix_default_language=True
)

## What I missing?
tks for your attention!!!

**Comment by fabiocaccamo** [comment]
@saymoncoppi have you set `settings.USE_I18N = True`?

**Comment by saymoncoppi** [comment]
Hello!!! 
Yes... it's enabled:

USE_I18N = True
USE_L10N = True
USE_TZ = True

**Comment by saymoncoppi** [comment]
Hey, can we check this? It keeps hidden :(

**Comment by fabiocaccamo** [comment]
This is really strange, you could debug this by doing:
- Open the admin interface package inside your virtualenv `lib/python3.?/site-packages/admin_interface/templatetags/admin_interface_tags.py`
- Add some logs before `return None` statements inside `get_admin_interface_languages` template tag function.

You should understand easily what condition is not satisfied.

**Comment by fabiocaccamo** [comment]
@saymoncoppi any feedback?

**Comment by fabiocaccamo** [comment]
Feel free to re-open this issue whenever you will have a useful feedback.

**Comment by jeroenpeters1986** [comment]
Hi @saymoncoppi I had the same issue, and thanks to @fabiocaccamo's helpful comment about the logs, I figured out that I needed to take a few extra steps and now it works!

To start off: my Django Version is 3.1, Python 3.9

I was missing the url additions. This is how I got it to work (currently, I only use the admin, no front-end view yet)

**urls.py**
```
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
)
urlpatterns += [url(r'^i18n/', include('django.conf.urls.i18n')),]
```


**settings.py**
```
LANGUAGE_CODE = "nl"
TIME_ZONE = "Europe/Amsterdam"
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)
LANGUAGES = [
    ("en-us", _("English")),
    ("nl", _("Dutch")),
]
MIDDLEWARE += ['django.middleware.locale.LocaleMiddleware']
```

The Dutch locale is working perfectly btw (also in the url), it's auto-detected and displaying accordingly. 
In the header I now have the language chooser, which I have set to display in the theme properties

I hope this of use for the rest of the users, or for the docs.

Also; I like django-admin-interface, it just gives the admin the detailed little extra's, but not like a complete overhaul. That's great!

**Comment by fabiocaccamo** [comment]
@jeroenpeters1986 thanks for your feedback!

How did you managed multilanguage without having added i18n urls?

**Comment by jeroenpeters1986** [comment]
Hi @fabiocaccamo, the language was only just 'switched' with setting a new default `LANGUAGE_CODE`, so I could see all my translations, but at the moment there was no "user-way" to switch it. I think (but I didn't check at the moment) that the URLs were not affected (like it is now). I was just in too much of a rush I guess to do it the right way, which I think I did now :-)

**Comment by saymoncoppi** [comment]
Hello Fabio!
I found the answer [here](https://github.com/fabiocaccamo/django-admin-interface/issues/67#issuecomment-884655334)

just adding this code to url.py

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]
urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

Tks

**Comment by saymoncoppi** [comment]
Hello Fábio! I remembered to back here and suggest you to update the readme considering this tip:

Add this code to url.py

urlpatterns = [
path("i18n/", include("django.conf.urls.i18n")),
]
urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

Tks

**Comment by fabiocaccamo** [comment]
@saymoncoppi https://github.com/fabiocaccamo/django-admin-interface#language-chooser-not-showing
