### ISSUE TITLE
Add custom img to login page

### ISSUE THREAD

**Issue by saymoncoppi** [fabiocaccamo/django-admin-interface#116]
# Hello @fabiocaccamo !!!
I wanna share another idea to build additional settings on the theme editor.
- Add an option to pick a bigger/different image to apply at the login page;
- Add an option to remove the title beside the image at the login page;
- Add the language picker at the login page

**Comment by fabiocaccamo** [comment]
@saymoncoppi regarding the first 2 options, could you share an image of the result you would obtain?

Adding the language chooser to the login page could be done, it surely requires some css because the login page doesn't have an header, so it must be placed using a fixed position.

**Comment by saymoncoppi** [comment]
Hello @fabiocaccamo !!!
Something like this on a 1sr draft:
![image](https://user-images.githubusercontent.com/22059715/108506738-0df9c400-7298-11eb-9486-a2b236324a9c.png)

For a 2nd round maybe we could improve the img handler... I could write another day if you want.

About the language picker I thought  this way:
![image](https://user-images.githubusercontent.com/22059715/108507147-a3955380-7298-11eb-87a3-88ba124d4ea5.png)
Let me know what you think!
Tks for your attention :)

**Comment by fabiocaccamo** [comment]
@saymoncoppi what is the purpose of these images? Add them as body/navbar background images?
Frankly I'm not very convinced about the images, I think this starts to be a little bit out of scope, I had to think better about it.

I would place the language picker on top right, in the same position of the logged-in page.

**Comment by saymoncoppi** [comment]
I just reorganize the img features... you already have 2 of 3. :P
- the logo was renamed to navibar since it is showed there
- favicon now is closer the other images
- And added the login img

but those things are just sugestion... You already done an awesome job!!!

**Comment by fabiocaccamo** [comment]
@saymoncoppi I close this issue as it is not my intention to add custom image support to the login page.
