### ISSUE TITLE
Foldable-admin

### ISSUE THREAD

**Issue by saymoncoppi** [fabiocaccamo/django-admin-interface#117]
Hello @fabiocaccamo  
It is another feature that I believe will work great if was builted-in admin-interface natively.
## Take a quick look:
https://github.com/deniskrumko/django-foldable-admin 
... the original repo seems unmaintained

**Comment by fabiocaccamo** [comment]
This is a nice feature that I already have on my mind.

**Comment by saymoncoppi** [comment]
Hello Fabio!!!
Today I saw an improvement that fits with this old suggestion.
Beyond the foldable option could the django-admin-interface offer a way to reorder classes on tree menu. Take a look 
https://stackoverflow.com/questions/398163/ordering-admin-modeladmin-objects

![image](https://user-images.githubusercontent.com/22059715/140752908-888c6d82-d1d1-41f5-8fa5-f9ac28ba6ac1.png)

**Comment by fabiocaccamo** [comment]
@saymoncoppi this is surely possible, but you should open another issue for it.

**Comment by merwok** [comment]
I’ve read this ticket and the commit but am still not sure what the feature is 😄 
The help text only says `foldable apps` but what’s that?

**Comment by fabiocaccamo** [comment]
<img width="619" alt="Screenshot 2021-11-24 at 16 27 37" src="https://user-images.githubusercontent.com/1035294/143266932-c95a4df0-7c85-405e-a010-ea1b21761239.png">
