### ISSUE TITLE
Support Changing icons

### ISSUE THREAD

**Issue by atkawa7** [fabiocaccamo/django-admin-interface#118]
<img width="185" alt="image" src="https://user-images.githubusercontent.com/5673828/109621560-cc90d080-7b43-11eb-8ff4-8283e6009ed8.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/5673828/109621775-12e62f80-7b44-11eb-9d10-4d60fdaa28d3.png">

Thank you for such an amazing library. Just wondering does DAI support overriding icons

**Comment by fabiocaccamo** [comment]
@atkawa7 thank you!
Actually this is not supported and I've never had the need to change icons.
If you do that, feel free to submit a PR.

**Comment by atkawa7** [comment]
@fabiocaccamo Thank you for the response. I was  thinking like changing the color of the icons and not the actual icons

**Comment by fabiocaccamo** [comment]
@atkawa7 ah ok, I understand! 
Yes, I already wanted to do it, but the color is inside the svg, so it is not very easy to override it. 
A workaround could be to override the icons color using a css filter like `filter: sepia(100%) saturate(300%) brightness(70%) hue-rotate(180deg);` and the rotating the hue to change the control the final color, but with this solution it is very hard to set the obtain the color dynamically, btw this could be achieved easily using sass.

**Comment by atkawa7** [comment]
Thank you @fabiocaccamo. I am closing this as it is difficult to fix.

**Comment by fabiocaccamo** [comment]
@atkawa7 as you prefer, if you any idea or solution re-open this issue.
