### ISSUE TITLE
Support Centering Logo

### ISSUE THREAD

**Issue by atkawa7** [fabiocaccamo/django-admin-interface#119]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/5673828/109917657-5cf32080-7cbe-11eb-93f6-318f22969c2c.png">

**Comment by fabiocaccamo** [comment]
Why? The admin layout is left aligned.

**Comment by atkawa7** [comment]
I just uploaded the logo but it seems the logo is left aligned. Is there an attribute to center logo

**Comment by fabiocaccamo** [comment]
Yes, it is left aligned, there is not any option to center it.

**Comment by atkawa7** [comment]
I see. Thanks @fabiocaccamo.
