### ISSUE TITLE
Django ModelChoiceField enhancement

### ISSUE THREAD

**Issue by mdtausifiqbal** [fabiocaccamo/django-admin-interface#121]
Please customize the ModelChoiceField, like that

- Input Text with input group of img of Object Chooser Instead of Add and Edit button.
- When A User Click on Choose Object, a modal should be appear with a list of Records *So that User Can Search Records or filter records to choose object*
- And Add and edit button should be Inside Modal of Object Chooser.

This feature can be found in CRM Systems.

**Comment by mdtausifiqbal** [comment]
![IMG_20210319_234003](https://user-images.githubusercontent.com/33699526/111824870-c1dc8680-890c-11eb-99cd-757fdeca98bf.jpg)

Just like in the screenshot.

**Comment by merwok** [comment]
Can you say more about the use case?

With recent Django, related fields for example already have a search input with autocomplete.
Is this request for strings with known values?

**Comment by mdtausifiqbal** [comment]
You can inherit the The Modal Dialog that i am saying from Just like table of records that was showing by Django in Model View Page.

This will be helpful for user experience, so that User can easily find the records in a large datasets rather than finding records in a dropdown list.

# What will User see in that
1. A Records Create and edit,and Search button in top of dialog
2. A Table of That Model with Many Columns
3. Filtering option in every Columns header (Just like MS Excel)
4. Sorting Option in every Column (Just like Jquery Datatable)
5. Two buttons Ok and Cancel in the bottom of Dialog

# Use case of Object Chooser Dialog
1. User Can Create and edit records from same dialog
2. User Can Perform Filtering action on Multiple Columns
3. Either User Can Perform a Manual Search Query (for example, Products.Name *Contains* "Box" *AND* Products.Price *>=* $10)
4. Above Query will be perfomed for Every Column
5. After Searching or filtering the records User Can Select particular record and Will Click Ok to Select that records
6. After Selecting records, A String Value of That Object will be shown in InputText widget


- I hope you will the understand the needs
- These features are already implemented in Many CRM System, Just Like Oracle Siebel, SAP Customer for Cloud e.t.c

**Comment by merwok** [comment]
Sorry, I don’t understand the request, and it feels like you didn’t get what I said about the existing functionality of django’s [autocomplete fields](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) that already use a nice [interactive select](https://select2.org/getting-started/basic-usage) widget.

I’m not a project maintainer so I’ll drop off now and let Fabio comment.

**Comment by fabiocaccamo** [comment]
@mdtausifiqbal what you are asking for is already possible using using autocomplete fields. Please follow the @merwok advice.
