### ISSUE TITLE
Support 3.2 dark mode, or properly override it

### ISSUE THREAD

**Issue by bastiaan85** [fabiocaccamo/django-admin-interface#124]
**Python version**
3.8.9

**Django version**
3.2.0

**Package version**
0.16.0

**Current behavior (bug description)**
Using a desktop dark mode setting, observed by the browser through css property `prefers-color-scheme: dark, the fact that [3.2 includes a dark admin theme](https://code.djangoproject.com/ticket/31259) results in a black background when using the included themes. For example with the "bootstrap" theme the purple text is almost unreadable. This requires manual endeavors to create a 'working' theme, but then for light mode users the theme is overly 'white'. In other words: django-admin-interface doesn't seem to support the hybrid themes included in 3.2.

**Expected behavior**
The themes should either be made dark mode compatible (preferred) or enforce the classic white background (and possibly other light css properties too) to prevent 3.2's dark mode theme to interfere. Better to have a functional light theme regardless of the desktop setting than a combination of dark and non-dark elements rendering the UI as hard to use.

**Comment by ChrisCrossCrash** [comment]
I'm also having this issue.

Just to show what @bastiaan85 is talking about, this is what the login page looks like with the default theme if your browser is set to preferring dark schemes:

![image](https://user-images.githubusercontent.com/40023417/113870299-5b83af00-97ba-11eb-9408-a6014c862486.png)

Could anybody figure out a quick workaround for until this gets a fix?

**Comment by fabiocaccamo** [comment]
@bastiaan85 @ChrisCrossCrash you can upgrade to `0.16.1` version.

**Comment by ChrisCrossCrash** [comment]
@fabiocaccamo That was fast! Thanks!
