### ISSUE TITLE
Improve logo appearance on retina displays.

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/django-admin-interface#127]
Using a jpg/png logo doesn't work very good. 

Problem:
- if the logo is 1x it's fuzzy on retina devices
- if the logo is 2x it's too big on non-retina devices

Possible solutions:
- Add `logo_width` and a `logo_height` fields to the model, in this way it is possible to use a 2x logo and its size will be forced.
- Add `logo_2x` field and display it using `srcset="{{ theme.logo_2x.url }} 2x"`
- Css-only solution: [detect retina devices](https://css-tricks.com/snippets/css/retina-display-media-query/) (a little bit dirty) and automatically resize logo width to 50% (only if not .svg). The drawback is that 1x images will be half-size on retina display, this is not very backward-compatible.

@merwok @merwok I would like to listen your opinion to take the best decision on how to solve this.

**Comment by merwok** [comment]
Uploading two images for 1x and 2x resolution seems straightforward.

Pure CSS solution using media queries does not seem dirty to me!  But reducing small images doesn’t sound great, so an explicit image field or checkbox would be better.

In one project I have customized the login page to use a fixed size for the logo, which is a big image.  It looks nice on mobile, classic monitor or retina.

![login](https://user-images.githubusercontent.com/635179/117371676-4c198380-ae96-11eb-8b78-f509e74a89fe.png)

**Comment by fabiocaccamo** [comment]
@merwok I am convinced that the best thing is to add 2 optional fields `logo_width` and `logo_height`, this solution would work very well even in case of .svg logos (I use them very often).

**Comment by fabiocaccamo** [comment]
Feature available within `0.17.0` version.
