### ISSUE TITLE
Migrations Hang

### ISSUE THREAD

**Issue by MNeipp** [fabiocaccamo/django-admin-interface#131]
**Python version**
3.7.11

**Django version**
3.1.8

**Package version**
0.16.3

**Current behavior (bug description)**
When an app is setup with multiple databases, migration 0020_module_selected_colors hangs indefinitely until timeout. Likely due to the migration not using `db_alias = schema_editor.connection.alias`, and then on line 13 not including `.using(db_alias)` as part of the python script to run

**Expected behavior**
Migrations should run smoothly and not hang.

**Comment by fabiocaccamo** [comment]
@MNeipp thank you for reporting this and for the PR.

Since this migration has been generated automatically by django, this seems to be a django bug, consider to report it to django project too.

**Comment by merwok** [comment]
If we’re talking about #132 then the issue was in a RunPython step which (to the best of my knowledge) are written by hand.

**Comment by MNeipp** [comment]
Merwok is correct; it has to do with how the RunPython operation was written. Thanks for accepting the pull request!

**Comment by MNeipp** [comment]
@fabiocaccamo Any chance you could release this new update to PyPi? I've tried building it straight from the git master, but some of my dependancies really don't like that for some reason. Thanks!

**Comment by fabiocaccamo** [comment]
@MNeipp sorry for the late reply, you can upgrade to `0.16.4`.
