### ISSUE TITLE
TemplateDoesNotExist at /admin/admin_interface/theme/1/change/

### ISSUE THREAD

**Issue by rdurica** [fabiocaccamo/django-admin-interface#133]
**Python version**
3.9.5

**Django version**
4.0.a1

**Package version**
0.17.0

**Current behavior (bug description)**
From django 4.0 package "colorfield" is not required and must be removed from INSTALLED_APPS. But with 4.0 is still needed see screen bellow:
https://github.com/fabiocaccamo/django-admin-interface/blob/a2329fdae567d3f5cf61ef0485f035d476cc6e83/admin_interface/settings.py#L26

![Screenshot ](https://user-images.githubusercontent.com/16089770/134421311-cf6bb864-95d3-497d-81bf-5817ae05d10b.png)

**Expected behavior**
remove condition for colorfield package

**Comment by fabiocaccamo** [comment]
Fixed within `0.17.1` version.
