### ISSUE TITLE
django.db.utils.ProgrammingError: relation "admin_interface_theme" does not exist

### ISSUE THREAD

**Issue by huxaiphaer** [fabiocaccamo/django-admin-interface#135]
**Python version**

Python 3.8.5

**Django version**
3.1

**Package version**
django-admin-interface==0.17.3

**Current behavior (bug description)**
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "admin_interface_theme" does not exist

**Expected behavior**
It should run the migrations

**Comment by merwok** [comment]
What command(s) do you run to get this exception?

Have you changed `INSTALLED_APPS` and run migrations?

**Comment by fabiocaccamo** [comment]
@huxaiphaer I close this due to lack of feedback, feel free to provide more useful informations and I will re-open it.
