### ISSUE TITLE
Language chooser style

### ISSUE THREAD

**Issue by saymoncoppi** [fabiocaccamo/django-admin-interface#136]
Hello Fabio!
Could you gimme a tip about how to overwrite the language_chooser.html (venv\lib\python3.6\site-packages\admin_interface\templates\admin_interface\language_chooser.html) and keep it this way below?

![image](https://user-images.githubusercontent.com/22059715/141237600-33f3a645-f856-453d-8700-5508fd871497.png)

I made these changes, but how to persist in a new enviroment? Manually again?
```
<select name="language" onchange="document.getElementById(String('language-chooser-hidden-form-' + this.value)).submit();" 
style="width:65px;margin-top:-9px;font-size:11px;font-weight:300;color:#cfcfcf;border:0px;outline:0px;">
```

Tks buddy!!!

**Comment by saymoncoppi** [comment]
Should I update the admin-interface.css and run **python manage.py collectstatic** again?

```
.admin-interface .language-chooser {
    display: inline-block;
    position: absolute;
    top: 15px;
    right: 15px;
    z-index: 10;
    width:65px;
    margin-top:-9px;
    font-size:11px;
    font-weight:300;
    color:#cfcfcf;
    border:0px;
    outline:0px;
}
```

**Comment by fabiocaccamo** [comment]
@saymoncoppi basically you need to customise the language-chooser css, I think the only thing you can do to persist changes is to override the template from you own application adding a `templates/admin_interface/language_chooser.html` file and injecting the css inside it, this file will override the `admin_interface` one.

Just for curiosity, why you need to change the language-chooser style? 
Maybe that an option to see it with a minimal style could be added.

**Comment by saymoncoppi** [comment]
Hello Fabio!
Since I'm using a **minimalist style** on the admin_interface theme, removing borders and adjusting the font size/color it fits better to me. 
Also maybe it is better for more people that prefer a non-distraction element at the top :)

Your idea about templates is the right way to do it. LOL 
Sorry for my newbie question.

Ahhh! Another suggestion to new versions of admin interface on language_chooser:

- Inline option for languages
- no borders for dropdown
- country flags option (only flags or beside language)

**Reference for flags:**
- [flag-icons](https://github.com/lipis/flag-icons)
- [agusmakmun](https://agusmakmun.github.io/python/django/2020/07/28/how-to-custom-select-language-icon-in-django-administration.html)
- [automationpanda](https://automationpanda.com/2018/04/21/django-admin-translations/)

One more time! 
## Tks for your great job!!!

**Comment by merwok** [comment]
Please don’t use country flags to represent languages: http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

**Comment by saymoncoppi** [comment]
G

> Please don’t use country flags to represent languages: http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

Great point! Tks for share... @fabiocaccamo discard the flags idea :)

**Comment by fabiocaccamo** [comment]
@saymoncoppi I would add an option named `language_chooser_widget` with 3 options:
- **Default Select** - the current one
- **Minimal Select** - the suggested one, requires just a dynamic css class
- **Inline Menu** - this is a completely different widget and it needs a bit of work because setting the language requires interaction with the hidden form, check: `templates/admin_interface/language-chooser.html`

**Comment by fabiocaccamo** [comment]
@saymoncoppi added support to custom language chooser style in `0.21.0` version. 

If you need a style that is not supported you must override the template: `templates/admin_interface/language-chooser.html`.
