### ISSUE TITLE
Replace travis with github actions

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#142]
Most projects have left Travis because of the management issues.
It seems that tests for PRs here are not run any more.
I could convert the config to github actions (example conversions from circleci: https://github.com/caravancoop/configstore/pull/47)

**Comment by fabiocaccamo** [comment]
@merwok it is already in my intentions to switch from travis to GitHub actions.

I saw that there is something to use tox in the GitHub action to avoid the matrix duplication.

If you can do it I really appreciate it and then propagate it to all other django packages.

**Comment by merwok** [comment]
There’s tox-gh-actions which works in many cases but has some issues (so I didn’t use it in the project I linked):
https://github.com/ymyzk/tox-gh-actions/issues/66
https://github.com/ymyzk/tox-gh-actions/issues/44

I think a strategy could be to use the matrix config to list all testenvs that are wanted, and remove them from tox config.  The `envlist` setting can list the testenv(s) to use when someone runs `tox` without parameters (for local dev), it is not required to contain all permutations.  I’ll experiment in some days!

**Comment by fabiocaccamo** [comment]
@merwok in the end I used `tox-gh-actions`, there are more pro than cons, and it is easier to maintain it on multiple packages.

**Comment by fabiocaccamo** [comment]
@merwok after the migration from TravisCI to GitHub actions, coverage reports are no more uploaded to codecov, have you any idea of what the cause could be?

**Comment by merwok** [comment]
I’ve only used codecov indirectly in companies, don’t have it for my personal projects.
(I look at HTML report locally and text report in CI, with covered file omitted and missing lines reported, so I find it enough)

I think there have been a few security issues with codecov recently, so I don’t know if I would spend time to use it.

**Comment by fabiocaccamo** [comment]
@merwok FYI I published an action for defining a matrix like the following one directly in the GitHub workflow: https://github.com/marketplace/actions/create-matrix-action

```
python-version {3.7}, django-version {2.0,2.1,2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
python-version {3.8}, django-version {2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
python-version {3.9}, django-version {2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
python-version {3.10}, django-version {3.2,4.0}, database {sqlite,mysql,postgres}
```

Any feedback/contribution is appreciated.

**Comment by merwok** [comment]
I like the idea of using strings to define matrix lines!
I don’t see a `matrix.json` file in the action repo or this one, so that part is confusing.

(Minor feedback: `cat` is used to concatenate files, not stream one file — [UUOC](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat) 😉)

**Comment by fabiocaccamo** [comment]
The `matrix.json` file is generated by the workflow [script](https://github.com/fabiocaccamo/create-matrix-action/blob/main/script.py) on the fly, only to be able to read the generated matrix using `${{fromJson(needs.create_matrix.outputs.matrix)}}` in the next step. (check [here](https://github.com/fabiocaccamo/django-admin-interface/blob/master/.github/workflows/test-package.yml#L42)). 

Probably it is possible to avoid the json file creation and set the script output directly to and `env` variable.

How can I set the variable value with the file content without using `cat`? *(I'm not skilled on this part)*

**Comment by merwok** [comment]
> Probably it is possible to avoid the json file creation and set the script output directly to and env variable.

GitHub Actions don’t have to save everything in env vars like other CI systems, they have the nice `output` system to pass data between jobs!

For `cat`, the wikipedia article I linked discusses alternatives.

**Comment by fabiocaccamo** [comment]
> GitHub Actions don’t have to save everything in env vars like other CI systems, they have the nice output system to pass data between jobs!

I compute the matrix json in the action `script.py` file, do you know if it is possible to set the output variable directly from inside the script?

**Comment by merwok** [comment]
If the script prints its output to stdout with the right `::thing` prefix, the data should be captured as an output!

**Comment by fabiocaccamo** [comment]
@merwok done: https://github.com/marketplace/actions/create-matrix-action

**Comment by merwok** [comment]
Ah that’s great!  Thank you for making that action!

**Comment by merwok** [comment]
I quite like it!  https://github.com/caravancoop/configstore/runs/5495913834

Wonder if something can be done to make the docker image pre-built (22s to build now)

**Comment by fabiocaccamo** [comment]
Maybe caching the output matrix using the matrix input as key?

**Comment by fabiocaccamo** [comment]
@merwok have you found a way to cache the docker image / output matrix?

**Comment by merwok** [comment]
Haven’t had the opportunity to look at it.
Could have a look at https://github.com/marketplace/actions/docker-layer-caching
