### ISSUE TITLE
Font Size selector

### ISSUE THREAD

**Issue by saymoncoppi** [fabiocaccamo/django-admin-interface#144]
Hello everyone!
Someone already thought about adding on admin-interface a font size selector?

I see two ways to do that:
1 - only using css/js over the template, allowing users to select their preference 
2 - plan to add on admin-interface settings to allow only the admin for those changes.

Simple way do handle with option n1:
https://codepen.io/webstudiosolutions/pen/WEOOPQ

What do you think?

**Comment by fabiocaccamo** [comment]
@saymoncoppi frankly I never had this need, generally I control the font size using `cmd`+`+` and `cmd`+`-`.

**Comment by saymoncoppi** [comment]
> @saymoncoppi frankly I never had this need, generally I control the font size in the browser using `cmd +` and `cmd -`.

M2, regular user doesnt know the tricks.

But it is just a suggestion considering UI/UX and how to delivery a great standard template.

If it´s not necessary, ok! Tks for the answer :)

**Comment by fabiocaccamo** [comment]
@saymoncoppi I don't know if the current admin uses `px`, `rem` or `em`. 

If it uses `rem` or `em` it should be very easy to add this feature. 

I would add just a `CharField` with choices: 90%, 100%, 110%, 120% and so on... 
No custom widgets that are hard to test and maintain along the time.

**Comment by fabiocaccamo** [comment]
@saymoncoppi `font-size` is expressed in `px` almost everywhere, it means that implementing this would be a nightmare.
