### ISSUE TITLE
Comma missing in MIDDLEWARE_CLASSES breaks things for Django <2

### ISSUE THREAD

**Issue by code-review-doctor** [fabiocaccamo/django-admin-interface#145]
The lack of comma here on line 43:
https://github.com/fabiocaccamo/django-admin-interface/blob/c9f0795a9508a21b921d291c159a0e9fdafdc1a1/tests/settings.py#L41-L46

results in implicit string concatenation, so `'django.contrib.messages.middleware.MessageMiddleware'` will get concatenated with the next line `'django.contrib.sessions.middleware.SessionMiddleware'`, resulting in Django attempting to import a class from `'django.contrib.messages.middleware.MessageMiddlewaredjango.contrib.sessions.middleware.SessionMiddleware'`, which will of course fail.

It looks like Django <2.0 is still supported so I think this should be fixed
https://github.com/fabiocaccamo/django-admin-interface/blob/master/setup.py#L53

I can make a PR for you :)

**Comment by fabiocaccamo** [comment]
@code-review-doctor thanks for reporting this.
