### ISSUE TITLE
Make logo / title clickable

### ISSUE THREAD

**Issue by mjwalter** [fabiocaccamo/django-admin-interface#146]
I'd like to make the logo / title clickable, so that it brings you back to the Django admin homepage. This is standard practice for making websites easy to navigate, and should be fairly simple to implement.

**Comment by fabiocaccamo** [comment]
@mjwalter I agree!

**Comment by fabiocaccamo** [comment]
@mjwalter you can upgrade to `0.18.4` version, thank you for the PR!
