### ISSUE TITLE
Change `font-family` from admin page

### ISSUE THREAD

**Issue by ChrisCrossCrash** [fabiocaccamo/django-admin-interface#148]
First of all, thanks @fabiocaccamo for this wonderful admin interface! It's always one of the first things I set up when I create a new Django project, and my users love the look and feel as well.

I was wondering, would it be feasible to add a `font-family` option? It would be very nice to match the font-family of the front end with the admin page. Perhaps it could be made to work with Google Fonts. That way, the admin page user would simply need to type in the name of the font and the font URL. For example, the font family name "Lato" and the URL "https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" effectively gives this output:

```html
<head>
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">
  <style>
    body {
      font-family: 'Lato', sans-serif;
    }
  </style>
</head>
```

Thanks for your consideration :)

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash thank you, I'm glad you enjoy it! 

Font customization would be surely a nice new feature *(check also #144)*.

There are different possible solutions for customizing the `font-family`, just to mention some of them:

- Google fonts
- Adobe Typekit
- Custom uploaded fonts
- Only default system font
- ...

Saying that one is better / more correct than another would be wrong, it is hard to decide which solution should be implemented here.
 
Probably the old good file upload is the best solution here, just to avoid the implementation of many providers.

**Comment by ChrisCrossCrash** [comment]
I agree that the file upload would be a great choice. Not to complicate things, but would it be possible to add multiple font files? This would allow you to add different font weights and fallback options for file formats. For example, you add a new font "Lato", and then `Lato-400.woff2`, `Lato-700.woff2`, `Lato-400.woff`, and `Lato-700.woff` as files for that font.

I think it would still work with just one file. Most browsers can still ["fake" a differently weighted font](https://stackoverflow.com/questions/23888977/how-do-browsers-change-font-weight-if-its-not-present-in-the-current-font). Also, woff2 format fonts are [pretty well supported](https://caniuse.com/?search=woff2), and I think the browser would just fall back to the next font in `font-family` if the file format isn't supported. You would just need to provide a fallback.

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash I'm not sure about this feature, it is not easy to find a good and simple solution that fits all scenarios. 
Said that, to give the total flexibility to any side-case, probably the best solution would be to support a custom css file (check #138).

**Comment by ChrisCrossCrash** [comment]
@fabiocaccamo I think adding a textarea for custom CSS would be an amazing idea! That way you could simply just drop in whatever CSS you want, like:

```css
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

body {
  font-family: 'Lato', sans-serif;
}
```

Not to mention the customization would be limitless. No need for custom templates or anything like that. So I'm totally on board for #138.

I noticed there was some discussion about compatibility. Perhaps the text area could get some help text. Something like:

> Using custom CSS may have unintended consequences. Use at your own risk.

**Comment by fabiocaccamo** [comment]
@ChrisCrossCrash I'm just afraid that the possibility to add custom CSS will make people less collaborative on proposing new features and reporting issues.

**Comment by ChrisCrossCrash** [comment]
@fabiocaccamo That's a good point.

I'll just make a custom template when the need arises. Thanks for your consideration on this issue! I'll close it now.

**Comment by merwok** [comment]
In an ideal world, a feature for custom CSS would be a good tool for people, letting them do site-specific things without having to redefine the base admin template, and if they find a common need (like clickable logo or dark mode) then they would still come here to request it.

I have defined a base admin template for custom CSS and JS, and I have opened tickets here!
