### ISSUE TITLE
Favicon and logo work for the very first form submit only!

### ISSUE THREAD

**Issue by Sam231221** [fabiocaccamo/django-admin-interface#155]
**Python version**
3.9

**Django version**
4.0

**Package version**
0.18.6

**Current behavior (bug description)**
  There's an issue generated about the image format is not correct(This works fine for the very first form submit only). Even though correct and requested image size is submitted, the field throws error to me.

**Expected behavior**
?

**Comment by fabiocaccamo** [comment]
@Sam231221 please provide more useful informations and the steps to follow to reproduce the bug you reported.

**Comment by Sam231221** [comment]
There's some issue with uploading favicon and logo. When you first upload favicon and click on the save button, It works fine. Next time when I revisit the theme and click on the save button, the form throws me errors. Here's what I got:

![Capture2](https://user-images.githubusercontent.com/70689865/154956144-c10e4445-7673-4c41-b3a7-64ac8e7772b2.PNG)


![Capture](https://user-images.githubusercontent.com/70689865/154955538-755eda73-ed9b-48d6-9bb3-a6929a59961a.PNG)

**Comment by Sam231221** [comment]
I have send preview of errors in Github.

**Comment by merwok** [comment]
The error message tells you what the problem is: this package relies on file extensions (a windows concept) to determine if the uploaded files have a valid type.  There could be a different choice (check the file contents, like what’s done on linux), but this one makes sense as most web servers will rely on the file extension to serve the uploaded files with the right content-type header.

So in short, rename your file `favicon-32x32_bpwnta.png`

**Comment by Sam231221** [comment]
> The error message tells you what the problem is: this package relies on file extensions (a windows concept) to determine if the uploaded files have a valid type. There could be a different choice (check the file contents, like what’s done on linux), but this one makes sense as most web servers will rely on the file extension to serve the uploaded files with the right content-type header.
> 
> So in short, rename your file `favicon-32x32_bpwnta.png`

The point to be noted is that I had uploaded images with the '.png' extension.  And that was what I got.

**Comment by fabiocaccamo** [comment]
@Sam231221 this package doesn't do anything special with uploaded files, are you using the default storage or a custom one?

**Comment by Sam231221** [comment]
> @Sam231221 this package doesn't do anything special with uploaded files, are you using the default storage or a custom one?

I am using the default storage.

**Comment by fabiocaccamo** [comment]
@Sam231221 could you check the path that is stored in the database please?
