### ISSUE TITLE
Provide ability to auto-complete or type-ahead all select fields

### ISSUE THREAD

**Issue by felixcheruiyot** [fabiocaccamo/django-admin-interface#156]
As the data grows, when filling a form with related fields, Django admin becomes very painful because it is hard to find a record or search without an auto-complete or type-ahead. Can you provide pointers on how to go about this if any? I'd be happy to help with the implementation.

Thank you
![autofill](https://user-images.githubusercontent.com/1054590/155497945-35b7c836-40eb-4b9e-a4c1-0f4a60b980f7.png)
.

**Comment by fabiocaccamo** [comment]
@felixcheruiyot you can use [`autocomplete_fields`](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) option.

**Comment by felixcheruiyot** [comment]
Thank you so much. Never knew this existed. I tried it and it works. My problem is solved.

Thanks.
