### ISSUE TITLE
Selected module doesn't round corners

### ISSUE THREAD

**Issue by smutrux** [fabiocaccamo/django-admin-interface#158]
**Python version**
3.10

**Django version**
4.0.3

**Package version**
0.19.0

**Current behavior (bug description)**
The corner radius for the selected module is always 0, even if rounded corners is selected
![image](https://user-images.githubusercontent.com/80628317/159014224-d772bb5d-2572-477e-a857-a1980cce1e66.png)

**Expected behavior**
The corner radius matches the radius of the module header and buttons

**Comment by fabiocaccamo** [comment]
This is just an highlighted background color for the selected item row, I think it is correct that it never has rounded corners, just like even rows.
Looking at your screenshot, I think you should probably use a lighten color.
