### ISSUE TITLE
I want to make django-admin interface on React-Material UI, 

### ISSUE THREAD

**Issue by anust** [fabiocaccamo/django-admin-interface#159]
please guide/ tell a way out how can I convert all the Django-admin pages in react front end.

**Comment by fabiocaccamo** [comment]
you should rewrite the whole admin using React-Material UI before and you can use css variables exposed by `django-admin-interface` for dynamic values.

**Comment by anust** [comment]
plz elaborate more, admin comes with default migrations. isnt it?

**Comment by anust** [comment]
ok, my app is like backend is on django and front end is on React, like this https://www.section.io/engineering-education/react-and-django-rest-framework/
what I want to do is, make the default admin panel and its functionality appear in my react theme. Is it possible? if so how?

**Comment by merwok** [comment]
The django admin is not a django API with a separate frontend, it’s django HTML views.  To replace it with a react app, you would need to write (or find) a package that exposes all admin functionality as API views, then write all client code to connect to that and display things.  django-admin-interface would not help you then, as it works with the django admin HTML views.  So it’s still not clear what you are after here!
