### ISSUE TITLE
Version 0.4.2 is incompatible with django-storages

### ISSUE THREAD

**Issue by browniebroke** [fabiocaccamo/django-admin-interface#16]
We deployed this on our live site today and it crashed our whole admin site, due to this change https://github.com/fabiocaccamo/django-admin-interface/commit/a09e13fb0070abcb9edac89060446e3aefdfa353#diff-e561f32039c364b52846f6a4931fd449R110

It crashing because we use S3 as media storage (from `django-storage`), which does not implement the `Storage.path` method, as per the Django base class docstring:
> Returns a local filesystem path where the file can be retrieved using Python's built-in open() function. Storage systems that can't be accessed using open() should *not* implement this method.

Reverting to the previous version of `django-admin-interface` (0.4.1) fixed the problem.

**Comment by fabiocaccamo** [comment]
Using `self.logo.path` instead of `self.logo.url` caused logo re-creation on each theme call (if using the default theme).
Could you add a test case for `django-storages`?

**Comment by fabiocaccamo** [comment]
Fixed in `0.4.3` version
(I quickly tested it on a project where I used `django-storages`)

**Comment by browniebroke** [comment]
Cool, thanks!
