### ISSUE TITLE
Raw id fields modal is not working

### ISSUE THREAD

**Issue by juanulis3s** [fabiocaccamo/django-admin-interface#161]
**Python version**
3.9.3?

**Django version**
3.2.9?

**Package version**
0.19.0?

**Current behavior (bug description)**
In admin.py when a field is set to use raw id fields the modal or pop up loads a login session. And the close the session. 
Please review the video.

**Expected behavior**
The pop up or modal should load the foreign key table.

https://user-images.githubusercontent.com/14265252/167223699-d9a587e8-3de2-4ec4-b958-4e55df1fc8f8.mov

**Comment by fabiocaccamo** [comment]
This is really strange.

- Have you followed correctly all the Installation steps? 
  https://github.com/fabiocaccamo/django-admin-interface#installation=
  
- Are there errors in the console?

- Could you tell me the classes of the element you are clicking?

**Comment by juanulis3s** [comment]
Hi thank you for your response.

I did follow installation correctly. Everything is working fine just that issue.

There are no errors in the console, only the following image after trying to login. 
![Screen Shot 2022-05-10 at 18 00 23](https://user-images.githubusercontent.com/14265252/167738505-dc3b8a49-4f51-4e38-8be0-b7e25f0c3227.png)

Firefox console display:
Content Security Policy: The options on this page have blocked the loading of an inline resource ("script-src").

The element I am clicking is:
```
<div>
    <label for="id_categoria">Categoria:</label>
    <input type="text" name="categoria" id="id_categoria" class="vForeignKeyRawIdAdminField">
    <a href="/admin/productos/categoria/?_to_field=id" class="related-lookup" id="lookup_id_categoria" title="Lookup"></a>
</div>
```

It is only working in chrome but it loads in admin dark mode.

**Comment by fabiocaccamo** [comment]
The error you show doesn't seem to be related to this package, you should check your django settings.

Have you run `python manage.py collectstatic --clear --noinput` ?

**Comment by fabiocaccamo** [comment]
@juanulis3s any update?
