### ISSUE TITLE
Modal windows doesn't work properly in Django 3.2

### ISSUE THREAD

**Issue by d3QUone** [fabiocaccamo/django-admin-interface#162]
**Python version**
3.8.12

**Django version**
3.2.13

**Package version**
0.19.1

**Current behavior (bug description)**
- Modal is aligned to the left
- Modal is very small, we can't move or resize it
- No controls on the modal
- Background is black

<img width="650" alt="Снимок экрана 2022-05-18 в 14 23 34" src="https://user-images.githubusercontent.com/4642885/169028796-5b04d603-595d-430e-afdd-23070184e11d.png">

<img width="600" alt="Снимок экрана 2022-05-18 в 14 23 45" src="https://user-images.githubusercontent.com/4642885/169028957-2efcd8ba-00a8-4ca3-a99b-8e3844836cb6.png">

**Expected behavior**
- It should be like before (we used Django==3.1.14 and django-admin-interface==0.15.1)

<img width="1000" alt="Снимок экрана 2022-05-18 в 14 33 48" src="https://user-images.githubusercontent.com/4642885/169029463-c5217ca1-be8c-4cf3-aafb-76d58dcd98c6.png">

**Comment by fabiocaccamo** [comment]
@d3QUone I'm personally using the latest version with django 3.2 and everything works well, could you ensure that:
- You have run `python manage.py collectstatic` 
- You have run `python manage.py migrate admin_interface`
- It is not a caching issue (try also to access the admin using another browser)

**Comment by d3QUone** [comment]
@fabiocaccamo thank you, `collectstatic` solved the problem for us!
