### ISSUE TITLE
{% extends "admin/base_site.html" %} loses header, sidemenu and breadcrumb

### ISSUE THREAD

**Issue by saymoncoppi** [fabiocaccamo/django-admin-interface#164]
Hello Fabio!
How can I extend {% extends "admin/base_site.html" %} on intermediate page for a custom action to show the admin side menu?
I used that previous command and got the style but lost the header, sidemenu and breadcrumb. 
Do you know how to apply those things?

tks

**Comment by fabiocaccamo** [comment]
@saymoncoppi have you tried this? 
https://github.com/fabiocaccamo/django-admin-interface#custom-base-sitehtml=

**Comment by fabiocaccamo** [comment]
@saymoncoppi any update?
