### ISSUE TITLE
Left/right scrolling broken with django-import-export

### ISSUE THREAD

**Issue by yatahaze** [fabiocaccamo/django-admin-interface#165]
I'm not sure which repo to open this issue on, but when using [django-import-export](https://github.com/django-import-export/django-import-export), after importing it takes you to a big table that shows the before & after. With this theme enabled, there is no ability to scroll left and right to see those changes.

Issue on the other side, just in case: https://github.com/django-import-export/django-import-export/issues/1476

**Comment by fabiocaccamo** [comment]
Hello @yatahaze 
thanks for reporting this, have you any public demo for checking the issue quickly?

**Comment by yatahaze** [comment]
Unfortunately I do not, but i could save html from a project of mine if that would help? Or I could inspect the code but I'm not sure what I'd be looking for...

**Comment by fabiocaccamo** [comment]
@yatahaze maybe just the html page is enough to debug the css quickly. I think a specific overflow css rule could easily solve this.

**Comment by fabiocaccamo** [comment]
@yatahaze have you found a CSS fix for this overflow issue? 
There is surely some `django-import-export` css class that can be used to fix this.

**Comment by yatahaze** [comment]
> @yatahaze have you found a CSS fix for this overflow issue? There is surely some `django-import-export` css class that can be used to fix this.

I do! Is there a way I can send it to you privately in case there's something revealing in it?

**Comment by fabiocaccamo** [comment]
@yatahaze sure, my email is public on my [profile](https://github.com/fabiocaccamo) page.

**Comment by yatahaze** [comment]
Sent!

**Comment by fabiocaccamo** [comment]
@yatahaze sorry for the late feedback.

What you sent me via email is not enough for debugging this problem, you should:
- Go to the admin page where there is the problem
- Save the admin page with the problem (saving the page you should have an html file and a directory containing all the assets used by the page)
- Zip the page and the assets folder and send them with me via email

**Comment by fabiocaccamo** [comment]
Fixed in de2979219e4fcf892bd76cba0dd192fa5e0ad5bd

**Comment by fabiocaccamo** [comment]
@yatahaze how did you added this?

<img width="323" alt="Screenshot 2022-10-07 at 11 20 54" src="https://user-images.githubusercontent.com/1035294/194520108-043b5c2e-fe4a-4b08-9504-9e316e0f535c.png">

**Comment by yatahaze** [comment]
Good question. I thought it was part of your theme? Haha

**Comment by fabiocaccamo** [comment]
It's probably a new django feature, didn't know about it!

**Comment by merwok** [comment]
Is that a filter for list filters??

Haven’t seen anything about that in 4.0 or 4.1 release notes.  Can you share the admin config for this?  (and your installed apps to see if it isn’t something third-party)

**Comment by yatahaze** [comment]
The filter is only for the sidebar on the left side of the screen to narrow down the list of models. It's not super useful because the headers stay behind after filtering. So if you have a lot of apps you still have to scroll a ton. (Maybe that could be fixed with this theme? :smiley:)

**Comment by fabiocaccamo** [comment]
@merwok it's a filter for the apps, already in my plans.
