### ISSUE TITLE
Add fieldsets collapsed default value option.

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/django-admin-interface#173]
**Ideas:**
- Default fieldsets collapsed value configured in `settings`.
- Default fieldsets collapsed value configured in the admin `Theme` options.
- Strictly Related to #160

**Comment by fabiocaccamo** [comment]
That would be great, and since there is JS involved for doing this I would add also:

👉 Storing locally each fieldset state (per model class), the cache key could be f"{app_name}-{model_name}-{fieldset_name}". #160

**Comment by merwok** [comment]
I’ll make a PR with the django script modified.

I will look at per-user state persistence in a separate commit.  Is there an easy way to get the theme option from JS?  Output it as a `data` attribute from a template?

**Comment by fabiocaccamo** [comment]
I don't think we need a per-user state persistence, I would store them using local storage (already did a similar thing for [foldable apps](https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/static/admin_interface/foldable-apps/foldable-apps.js) feature).
Exposing theme options as JS variables could be good and useful thing.

**Comment by merwok** [comment]
I meant that local storage is per-browser persistence, not adding a model with foreign key to user!

**Comment by merwok** [comment]
> Exposing theme options as JS variables could be good and useful thing.

I found the current technique in a template:
```
{% if theme.foldable_apps %} foldable-apps {% endif %}
```

Easy to use the same.

**Comment by merwok** [comment]
I don’t understand this sub-part of the discussion!

You requested to persist current collapsed state in local storage.  I said I don’t need that for my project but will add it.
Then I called that per-user persistence by mistake instead of per-browser, I wasn’t making a different proposal 🙂

**Comment by fabiocaccamo** [comment]
Ahh ok, now I understand!

**Comment by fabiocaccamo** [comment]
@merwok have you planned to work on #160 in the next days? 

I ask it to decide if publishing a new release with the latest features/bug-fixies today/tomorrow or waiting for this feature too.

**Comment by merwok** [comment]
If it’s very easy to make a release, then you could ship what’s already done now, then another one soon including the changes for #160 and #174 .  If it’s trouble, then you could wait to release next week with everything.
