### ISSUE TITLE
Make currently active list filters more visible

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#174]
On a list page with many filters shown and the dropdown option active, admin users have a hard time finding out which filters are currently active, in order to remove one for example if the current selection has no results.  They would have to go through the list and determine if the value visible is the default or not, so they end up clearing all filters (it’s the only action displayed) and re-building their selection.

Ideas:
- A: add CSS to highlight filters with a non-default value selected

- B: put active filters at the top of the list of filters

- C: on top of the filter list, show currently active filters with a link to remove each: `( Age: 9+  | x ) ( Group: 10-15  | x )`  (parens to represent a chip widget)

A + B or A + C are possible combinations.

I can contribute code if you agree to this feature!

**Comment by fabiocaccamo** [comment]
This is another good 
- A: I like this option, but I'm pretty sure that it's not possible to do that with CSS only.
- B: In terms of usability it looks a little bit wrong to me ...
- C: This would be cool, must be sure that the layouts work in different side cases (eg. values too long)

I'm for `A + C`, if you can contribute it would be great.

**Comment by merwok** [comment]
Yeah, A is custom template and CSS!

Let me make a first commit to add A (template + CSS + theme option), then work on C (no JS, custom template, if needed template tag, CSS for the chip styling, theme option)

**Comment by merwok** [comment]
Reopen this to add option for item C?

**Comment by fabiocaccamo** [comment]
Feature available by upgrading to `0.21.0` version.
