### ISSUE TITLE
Allow scrolling list filter box

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#175]
On a page with many objects and many filters (even with dropdown option active), the admin users have noticed that it’s not possible to scroll down the filter box until the rest of the page has scrolled to the bottom.

I am considering CSS changes to make the box scrollable (combination of max-height and overflow maybe?), or template changes to define collapsible sections (harder to integrate with the python code defining list_filter, also maybe not great UI), or a link to jump to the bottom of the list (weird).  First idea seems best to me; what do you think?

(Making this a bug report because it could be fixed without an option, and is not the same as feature request #163)

**Comment by fabiocaccamo** [comment]
Cool, nice catch! 
This could be easily fixed with CSS only.

**Comment by merwok** [comment]
Can you let me know if you’re able to address this easily, or if I should work on a PR?

(I tried very quickly some overflow/scroll-behavior/max-height option combinations without success, but could spend more time)

**Comment by fabiocaccamo** [comment]
I can do it!

**Comment by merwok** [comment]
I had forgotten about the sticky list filter option!
Disabling it means that the whole page now scrolls, main list and filter sidebar.  It’s all I need.

Feel free to close this!

**Comment by fabiocaccamo** [comment]
So is this a sticky filter bug?

**Comment by merwok** [comment]
You’re right, depending on the viewport height and the main section height, there should still always be an easy way to browse a sticky filter section.

**Comment by merwok** [comment]
Fixed by 990db6f !
