### ISSUE TITLE
Ensure no HTTP hyperlinks are used

### ISSUE THREAD

**Issue by Mesake94** [fabiocaccamo/django-admin-interface#179]
**HTTP hyperlinks in admin/base_site.html**

Calling resources over HTTP from within a HTTPS application could remove the TLS protection and potentially expose sensitive information in plain text.

**Comment by fabiocaccamo** [comment]
@Mesake94 please, list the resources that are loaded over http.

**Comment by merwok** [comment]
The template uses the template tag `static` to generate links, so if http links are generated it’s a problem in your site configuration (or reverse proxy config, or server config).

**Comment by fabiocaccamo** [comment]
@merwok thank you for the support!

**Comment by Mesake94** [comment]
Actually. I recently had a pen test on one of my projects and this was picked up. There are HTTP hyperlinks in base_site.html template.

**Comment by fabiocaccamo** [comment]
As you can see at line 17 there is the logo svg background image, the `http://` protocol appears in the svg xml attributes, no request is made.

**Comment by Mesake94** [comment]
Thanks @fabiocaccamo . It was not really a security vulnerability but a best practice issue.

**Comment by merwok** [comment]
What best practice specifically?  XML namespaces are opaque identifiers, it’s not possible to change the URL scheme.
