### ISSUE TITLE
Show active filters at the top of the sidebar with clear button

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#181]
On a list page with many filters shown and the dropdown option active, admin users have a hard time finding out which filters are currently active, in order to remove one for example if the current selection has no results. They would have to go through the list and determine if the value visible is the default or not, so they end up clearing all filters (it’s the only action displayed) and re-building their selection.

#174 improves the visibility and #175 fixes a usability issue.  This proposes a new theme option to also display current filters at the top of the sidebar, wich a link to remove each filter: ( x Age: 9+ ) ( x Group: 10-15 ) ( x Clear all filters ) (parens to represent a chip widget)

**Comment by fabiocaccamo** [comment]
I totally agree, the list filter would be much more usable. Having this feature would be great!

**Comment by fabiocaccamo** [comment]
Feature available in `0.22.0` version.

**Comment by fabiocaccamo** [comment]
@merwok this feature doesn't work with [django-rangefilter](https://github.com/silentsokolov/django-admin-rangefilter), it's not a big problem, but if it would work it would be great!

**Comment by fabiocaccamo** [comment]
It would be nice also having the possibility to remove the `date-hierarchy` filter.

**Comment by fabiocaccamo** [comment]
@merwok any progress on supporting `date_hierarchy` clearable list filter?

**Comment by merwok** [comment]
I haven’t had the time to look at django-rangefilter.

For date_hierarchy, how would you like it to work?  Remove the breadcrumbs links and integrate it in the sidebar, with a select or links depending on the theme option?

**Comment by fabiocaccamo** [comment]
Improving `django-rangefilter` compatibility is a low-priority task.

Supporting the django model admin `date_hierarchy` filter would be great.
I would keep the native date hierarchy breadcrumbs and I would add a link for removing the active date filter in the list filter (like you already did for other active filters).

**Comment by merwok** [comment]
Oh right, that seems best!  I’ll do it

**Comment by merwok** [comment]
Now that we have date hierarchy in the quick removal links, it seems strange that django just shows some dates without naming the field!  I can make a PR to add it, should it take a new Theme option or just be default?

Also I have looked at rangefilter but not adapted the style yet.

**Comment by fabiocaccamo** [comment]
I think that a default is enough here.

**Comment by merwok** [comment]
This little change is a bit heavy: I have to override the `admin/date_hierarchy.html` template used by the inclusion tag `date_hierarchy` to add a list item in the date `ul` but the context available does not include the changelist or model options, so I can’t get the field verbose name.

I would need to override a block in `admin/change_list.html` to use a custom template tag that calls the django tag and adds `date_label` to its context, which does not seem good.

Let me see if I can add something in `change_list.html` without touching the original template tag and template.  Adding a list item was easiest to get the right styling, but I’ll look at prepending another element with CSS positioning.  But don’t wait on this for the next release!

**Comment by fabiocaccamo** [comment]
> Now that we have date hierarchy in the quick removal links, it seems strange that django just shows some dates without naming the field!

What dates are shown without naming the field?
Does this problem affects only the field defined for `date_hierarchy`?

**Comment by merwok** [comment]
The date drilldown is a bar of links like `2021   2022` then if you pick one year you see `<All dates   2022  Oct 2022   Nov 2022` then it’s days.   I was talking about adding `Created date:` (the date hierarchy field verbose name)` before that, like we have in the filter quick removal link sidebar.

**Comment by merwok** [comment]
This should also show active search terms!

**Comment by fabiocaccamo** [comment]
It would cool, but I'm not sure the list filter is the right place for showing active search terms.

**Comment by merwok** [comment]
Not necessarily the full search terms, but `Search: ... ×`
For the same reason that we show active date filter there

**Comment by fabiocaccamo** [comment]
Should I reopen this issue?

**Comment by merwok** [comment]
If you want to!  I would also address range filters when I have the time to look at this.

**Comment by fabiocaccamo** [comment]
@merwok I close this issue since the main feature has been made, a PR for improvements will be welcome anytime.
