### ISSUE TITLE
Internalization : language code change issue

### ISSUE THREAD

**Issue by RajendraGupta22** [fabiocaccamo/django-admin-interface#182]
**Python version**
3.8.10

**Django version**
4.0.4

**Package version**
0.20.0

**Current behavior (bug description)**
defined models doesnt get converted to the change language
only in build models like 'User, Group' get converted to change language
the models defined in the new app doesnt get converted

**Expected behavior**
need to convert everything to change language

**Comment by fabiocaccamo** [comment]
@RajendraGupta22 this application doesn't manage translations, it just offers an admin control for switching the language by activating the selected one.
