### ISSUE TITLE
Refresh translations + add CI check

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#184]
I recreated translations last week and noticed many changes.

Files should be regenerated so that translators can update translations.
I will contribute French!

**Comment by fabiocaccamo** [comment]
I would be nice to automate this with a GH workflow.

**Comment by merwok** [comment]
Actually I think that translations should be updated by PRs adding new translatable strings, just like migrations.
There is a small drift now, it can have a one-time correction, then new PRs can have more vigilance (using a checklist or an automated checks).

**Comment by fabiocaccamo** [comment]
True, but in the end they are always forgotten. Maybe some automated CI checks would be useful.

**Comment by fabiocaccamo** [comment]
Maybe this could be done using [pre-commit](https://pre-commit.com/).

**Comment by fabiocaccamo** [comment]
@merwok there is a problem with the `lint` job: 
https://github.com/fabiocaccamo/django-admin-interface/actions/runs/3241468894/jobs/5313478719

**Comment by merwok** [comment]
Is it a problem?  The logs show that the line numbers have changed.
(In my projects I prefer to save file names but not line numbers)

**Comment by fabiocaccamo** [comment]
I have not touched anything related to translations, but now the CI fails (it worked at merge time).

**Comment by merwok** [comment]
Yes you have: adding two lines to base_site.html changes the line numbers recorded in PO files.
It is not a substantial change, but the tools can only report that it is a change.

Would you be ok to record file names without line numbers in the PO files?
Translators could still search in the files when they need more context, or benefit from `Translators:` comments (see this example I added: https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/templates/admin/change_list.html#L18 → https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/locale/fr/LC_MESSAGES/django.po#L261)

**Comment by fabiocaccamo** [comment]
I think that keeping line numbers is useful. I'm not convinced at all by this approach, it would be better to automatically update translations.

**Comment by merwok** [comment]
Updating translations is one step of the developer’s flow, like creating migrations and running tests.
Sometimes there are conflicts (fuzzy msgid because the original string was changed, or a new string looks like an old one) and the developer can fix them before commit.

This can be assisted by a tool (the `update-translations.sh` script I added), but not fully automated.

Maybe the check for translations should be done in release branches only, not in all PRs.  You could make a branch, update changelog and versions, refresh translations, give a day for translators to do their language, then merge and publish.

**Comment by fabiocaccamo** [comment]
True, but a little bit of more automation would help.
I added `pre-commit`, it is very easy to run also some custom script: 
https://stackoverflow.com/questions/59499061/how-to-run-custom-shell-script-file-before-pre-commit-hook#59499550

**Comment by fabiocaccamo** [comment]
I managed to make it working with `makemessages --all` then I removed the bash script.

**Comment by fabiocaccamo** [comment]
Hi @merwok, is it clear to you why the lint fails here: 
https://github.com/fabiocaccamo/django-admin-interface/actions/runs/3404943401/jobs/5669863026

**Comment by merwok** [comment]
The post step for the python action is this script: https://github.com/actions/setup-python/blob/v4.3.0/src/cache-save.ts

It seems that the error comes from parsing the list of paths to cache, but that list is defined by the action too so nothing to change in your config file 🙁 

Is this a one-off error or always happening now?

**Comment by fabiocaccamo** [comment]
It happens only in this branch because `dependabot` upgrades actions/requirements versions.

**Comment by merwok** [comment]
Does it run without the `cache` config?

**Comment by fabiocaccamo** [comment]
Removing the `cache` config only from the `lint` step it works.
