### ISSUE TITLE
welcome-msg duplicated

### ISSUE THREAD

**Issue by ps78674** [fabiocaccamo/django-admin-interface#185]
**Python version**
3.10.7

**Django version**
3.2.14

**Package version**
0.21.0

**Current behavior (bug description)**
The welcome message is duplicated.
![image](https://user-images.githubusercontent.com/31385755/195160264-742ea88c-4079-4bb0-901b-67c89f907ca8.png)
![image](https://user-images.githubusercontent.com/31385755/195160314-66881193-d423-4c99-8cb9-7b6816f85080.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/31385755/195160541-72f3b4b0-6a67-44b2-b74b-fd4b26395958.png)

**Comment by fabiocaccamo** [comment]
@ps78674 please fill the issue template when reporting an issue.

**Comment by ps78674** [comment]
> please fill the issue template

issue updated

**Comment by fabiocaccamo** [comment]
@ps78674 you can upgrade to `0.22.0` version.
