### ISSUE TITLE
Integration with django-filebrowser

### ISSUE THREAD

**Issue by pvanfas** [fabiocaccamo/django-admin-interface#188]
Styles are not applied to django-filebrowser pages
![image](https://user-images.githubusercontent.com/45325099/197471828-2b553123-dc7a-4c25-9cd2-b6e08ce7b7f9.png)

**Comment by fabiocaccamo** [comment]
@pvanfas styling all the most used third-party packages is a big work, and I have neither the time nor any financial support to do so.
Until now I styled the apps that I used/use, and `django-filebrowser` is not in that list. 

You could:
- submit a PR to this library for styling `django-filebrowser`.
- submit a PR to `django-filebrowser` for setting its style correctly when `django-admin-interface` is used
 
More info about the available variables for dynamic styling here: https://github.com/fabiocaccamo/django-admin-interface#add-theme-support-to-third-party-libraries
