### ISSUE TITLE
How to set up an external logo?

### ISSUE THREAD

**Issue by diogosilva30** [fabiocaccamo/django-admin-interface#189]
From what I have seen the logo has to manually uploaded. However, I would like to include a default logo in a static folder, and configure my default theme to use the path of the static folder.
Is there anyway to configure this behaviour?

**Comment by merwok** [comment]
You can do that by overriding the base template and redefining this block: https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/templates/admin/base_site.html#L153
