### ISSUE TITLE
Custom Admin Page

### ISSUE THREAD

**Issue by VaZark** [fabiocaccamo/django-admin-interface#197]
Hello !! I've recently discovered this project in my quest to reuse the admin page as much as possible for a minimal backoffice. I love that ability to theme and all the little features like dropdown for filters that make a big difference to UX.

**Requested feature**
Do you have any plans on adding support for a custom Admin Page? 

**Feature context**
Currently, I am hitting a wall with the reusability of the admin. I'd like to make custom pages with a custom queryset in order to have custom pages for KPIs and charts, internal forms and tiny little backoffice features.

A quick look at the code shows me that it needs to be an `admin_view` or tied to BaseModelAdmin. I'm currently working on trying to replicate it but it's a wip and I'm pretty lost haha

**What it brings to project**
This would be a major differentiator against the standard admin. Since, django admin comes loaded with default widgets and permissons, there is far less logic to be written if we need only a few custom pages for a backoffice. 

**Other solutions** : 
I've taken a look at [django-admin-views](https://github.com/koleror/django-admin-views) but I'm not been able to get it working so far. (I've raised a bug report at the moment)

<a href="https://dashboard.polar.sh/fabiocaccamo/django-admin-interface/issues/197">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/197/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/197/pledge.svg">
</picture>
</a>

**Comment by merwok** [comment]
I am not speaking for the project author, but my understanding is that this project is focused on improving UX and UI of the admin, not expand its functionality.

Other projects exist and add features:
- https://pypi.org/project/django-admin-relation-links/
- https://pypi.org/project/django-admin-actions/
- https://pypi.org/project/django-admin-tools/
- https://dev.to/sm0ke/django-admin-dashboards-open-source-and-free-1o80

**Comment by fabiocaccamo** [comment]
@VaZark I created this library to improve the default admin UI/UX trying to avoid to touch the admin logic.

If one day this library will be sponsored, maybe I will invest more time on it and start to add some useful features that could be useful in all projects, like custom views, sorting widgets, common useful actions, and so on...

Once I needed a custom view in the admin and I used [this app](https://github.com/pawnhearts/django_nonmodel_admin), it worked well, but now it no more maintained (I have some unanswered issues open).

**Comment by unknowncoder05** [comment]
Is there a way to pass the styles to a custom admin site created like this?

```py
class SecondAdminSite(admin.AdminSite):
    site_header = "admin v2"
    site_title = "Admin Portal v2"
    index_title = "Welcome to The Admin Portal v2"

homepage_admin_site = SecondAdminSite(name=second_admin_site')
```

**Comment by fabiocaccamo** [comment]
@unknowncoder05 the styles are passed at template level, unless you use a custom template the styles will be inherited.

**Comment by merwok** [comment]
The Theme class could be optionally linked to a Site model (from the django sites framework), which seems the way to do this kind of customizations.  But this is going away from the thing discussed in this ticket.

**Comment by fabiocaccamo** [comment]
@VaZark there are already some packages that can be used to integrate some custom pages:

- https://github.com/jsocol/django-adminplus
- https://github.com/lekjos/django-custom-admin-pages
- https://github.com/pawnhearts/django_nonmodel_admin
