### ISSUE TITLE
Minor CSS Alignment Fix

### ISSUE THREAD

**Issue by VaZark** [fabiocaccamo/django-admin-interface#198]
The inputs of inlines are not aligne along the same line

Django : 4.1.3
Python : 3.8

**Current behavior (bug description)**
![image](https://user-images.githubusercontent.com/11616688/201143461-1a46f940-1321-4ed1-a9a1-dd78783fed80.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/11616688/201143370-706cc134-5dca-4750-a8a2-18ac2081539f.png)

**Comment by fabiocaccamo** [comment]
@VaZark I'm aware of this problem, the bottom alignment is a workaround for displaying the `modeltranslation` widget aligned correctly, but where it is not present the alignment is bad as you reported.

A solution must be found, it must work well both with and without modeltranslation widgets in the inline.

Do you want / have time for working on this issue?
