### ISSUE TITLE
Avoid pinning dependencies (Discussion)

### ISSUE THREAD

**Issue by cmc333333** [fabiocaccamo/django-admin-interface#22]
Pinning dependencies to specific versions of upstream libraries is a good practice when we're writing an app, but not as useful when writing a library. If our dependencies are too strict, the users of our library may see a conflict with their own application (or another library).

Currently, we [pin](https://github.com/fabiocaccamo/django-admin-interface/blob/486bfa9aba0351b160de30f35077187847b10bfa/setup.py#L20-L22) versions of `django-colorfield`, `django-flat-theme`, and `django-flat-responsive`. I propose we instead specify minimum and maximum bounds.

What do you all think?

**Comment by fabiocaccamo** [comment]
You are right, I would specify min-max bounds.
