### ISSUE TITLE
Django-Streamfields Compatibility Issue.

### ISSUE THREAD

**Issue by jefffortune** [fabiocaccamo/django-admin-interface#228]
**Python version**
3.9

**Django version**
4.1

**Package version**
django-admin-interface 0.24.0
django-streamfield 1.4.4

**Current behavior (bug description)**
Using django-streamfields with basic out-the-box setup and using text only to eliminate any additional issues.
On the admin screen creating a new content page, I click to add a new block, 
![image](https://user-images.githubusercontent.com/17855589/207501348-e79125f1-f5f9-4e85-b9b6-0a0df210f546.png)
The block appears in the stremfield_app list as expected
![image](https://user-images.githubusercontent.com/17855589/207501414-0389f77e-4481-48a2-b7f7-29bb5f8a0cc3.png)
When clicking on add content, the modal does not open as expected.
However, I can click save, and after the page saves, I can now click the add content button and add the content for testing.
And the system adds the block as expected.
**Expected behavior**
After initially adding the block to the stream field app list I would expect clicking add content would open the modal so I can add content.

I can comment out admin_interface in installed apps and the basic Django admin works as expected.

**Comment by fabiocaccamo** [comment]
> When clicking on add content, the modal does not open as expected.

Probably there is an error in the browser console, could you check it please?

**Comment by fabiocaccamo** [comment]
@jefffortune I have been able to reproduce it.

**Comment by fabiocaccamo** [comment]
Fixed in `0.24.1` version.

**Comment by jefffortune** [comment]
Thank you very much for the speedy solution. I have tested this and can confirm it works as expected. Thank you again.
