### ISSUE TITLE
Multiple copies of django-logo.svg created

### ISSUE THREAD

**Issue by browniebroke** [fabiocaccamo/django-admin-interface#24]
When using this library with `django-storages` and [`AWS_S3_FILE_OVERWRITE=True`](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html?highlight=AWS_S3_FILE_OVERWRITE), the library creates (a lot of) copies of the image `django-logo.svg`. We had 20,000+ created in a few weeks time.

This `django-storages` setting is to make sure that an upload of a file will not override existing file. It's useful as many people might upload a file called "photo.jpg" for different purposes.

I suspect is due to the `Theme.get_active_theme()` which is used in many places:
- post_migrate signal
- post_save signal
- post_delete signal
- template tag

Also, `get_active_theme`, might call `set_active`, which calls save, which calls `get_active_theme`. Looks like there might be a case where it's called several times in a loop. From an API standpoint, it's a lot of things for a method which apparently is just "getting" something.

Maybe it would make more sense to not do too many things in that `get_active_theme` method, separate the auto-updates in a setter method and provide sensible defaults in the templates if no theme is provided (using `{{ color|default:"#0C4B33" }}`)?

Sorry for the long issue, happy to discuss further as well as helping with the implementation.

**Comment by fabiocaccamo** [comment]
Are you using the latest version of this lib? 
The .svg was removed [here](https://github.com/fabiocaccamo/django-admin-interface/commit/8a9842c2196b3dbb0594ef2078d6d9b1516ac3f1), I think the multiple copies was created before.

**Comment by fabiocaccamo** [comment]
@browniebroke if you have not any update about this issue I will close it.

**Comment by browniebroke** [comment]
Hi, I sorry missed this comment. Let me check again I will get back to you in the coming day or 2.

**Comment by browniebroke** [comment]
You're right, we recently upgraded from 0.4.4 to 0.5.0 and it appears that the problem is gone now. 
Thanks

**Comment by fabiocaccamo** [comment]
Good, thanks for the feedback.
