### ISSUE TITLE
Template tag raises exception

### ISSUE THREAD

**Issue by pandichef** [fabiocaccamo/django-admin-interface#241]
**Python version**
3.8.10

**Django version**
2.2.28

**Package version**
0.24.2

**Current behavior (bug description)**
`TemplateSyntaxError at /admin/admin_interface/theme/`
`Invalid block tag on line 8: 'translate', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?`
`In template /home/pandichef/.virtualenvs/pandifi23/lib/python3.8/site-packages/admin_interface/templates/admin/change_list.html, error at line 8`

I noticed `{# copied from django 4.0.7 #}` in the file.  So maybe 0.24.2 isn't compatible with Django 2.2.28.  I tried using older version of `django-admin-interface`, but I kept getting the error.

**Comment by merwok** [comment]
Oh, that’s an old version! https://www.djangoproject.com/download/#unsupported-versions
But django-admin-interface declares that it supports it.

I have checked the source code for built-in template tags in django 2.2 and the tag is named `trans`, not `translate`: https://github.com/django/django/blob/stable/2.2.x/django/templatetags/i18n.py#L316

In more recent versions, the recommended tag is `translate` with an alias `trans` that still works for compatibility.
So you could make a pull request to use the older form and that should work with all versions!
