### ISSUE TITLE
Multi tenancy support

### ISSUE THREAD

**Issue by smunoz-ml** [fabiocaccamo/django-admin-interface#242]
Hello! I want to use different themes based on a parameter in the database that differenciates the organization of the logged in user. The change has to be applied on the client side, because I do not want to change the other tenants interface. Is this possible with the library? Or maybe there is a way that I can do this using a complementary library?

Thanks in advance for this amazing library! 🙌🏻 

<a href="https://dashboard.polar.sh/fabiocaccamo/django-admin-interface/issues/242">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/242/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/242/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
Hi @smunoz-ml, 
this is a cool idea, but actually it's not supported.

**Comment by smunoz-ml** [comment]
Thanks for the quick response! I will try to find a workaround for now

**Comment by smunoz-ml** [comment]
No, I have one schema with a column in every table to identify to which tenant the data belongs to [as specified in the alternative C1 in this link.](https://dev.to/lbelkind/strategies-for-using-postgresql-as-a-database-for-multi-tenant-services-4abd). My tenancy system is database based.

**Comment by fabiocaccamo** [comment]
@smunoz-ml it should be easy to achieve this by extending [`ThemeQuerySet`](https://github.com/fabiocaccamo/django-admin-interface/blob/main/admin_interface/models.py#L12) overriding `get_active` method, then setting the customized queryset as default [objects](https://github.com/fabiocaccamo/django-admin-interface/blob/main/admin_interface/models.py#L385) manager for the `Theme` model.

**Comment by smunoz-ml** [comment]
> @smunoz-ml it should be easy to achieve this by extending [`ThemeQuerySet`](https://github.com/fabiocaccamo/django-admin-interface/blob/main/admin_interface/models.py#L12) overriding `get_active` method, then setting the customized queryset as default [objects](https://github.com/fabiocaccamo/django-admin-interface/blob/main/admin_interface/models.py#L385) manager for the `Theme` model.

This workaround only works server side, right? It doesn't work on the client side (Which is the side I want it to work)

**Comment by merwok** [comment]
It’s not clear what you are referring to with «client site», can you say more?

**Comment by smunoz-ml** [comment]
Is there a way to change the selected theme using JavaScript?

**Comment by fabiocaccamo** [comment]
> Is there a way to change the selected theme using JavaScript?

@smunoz-ml no, there is no way to change the selected theme using JavaScript.

I understand well the problem, a possible solution is what I suggested you here: https://github.com/fabiocaccamo/django-admin-interface/issues/242#issuecomment-1514288553 (I don't think it requires too much code).

Alternatively, maybe you can find some helpful informations in #77 (by [@isik-kaplan](https://github.com/isik-kaplan))
