### ISSUE TITLE
'Fieldsets as tabs' not working if there are non-ASCII symbols in fieldset name

### ISSUE THREAD

**Issue by amuzhdaba** [fabiocaccamo/django-admin-interface#247]
upd: ouch sorry for double

I think that Django template filter 'slugify' in change_form.html drops all non-ASCII symbols in fieldset name, so all such tab elements has similar id ('tablink-') in Dom and js can't switch tabs.

**Python version**
3.10

**Django version**
4.1.5

**Package version**
0.24.2

**Comment by fabiocaccamo** [comment]
@amuzhdaba why you closed this issue?

**Comment by fabiocaccamo** [comment]
Duplicate of #237
