### ISSUE TITLE
The version 0.4.6 is not creating the "0006_bytes_to_str.py" migration file. 

### ISSUE THREAD

**Issue by alcfernandes** [fabiocaccamo/django-admin-interface#25]
Hello.

The version 0.4.6 when it is installed is not creating the "0006_bytes_to_str.py" migration file. In the development environment this is not a problem, since the makemigration command generates the file. But I'm having problems in the production environment in Heroku, because it installs django-admin-interface during the deploy and the migrate command only runs the five available migration files. I can not run a makemigrations directly on Heroku. Can you help me?

**Comment by fabiocaccamo** [comment]
Hi, 
The version 0.4.6 does not include 0006_bytes_to_str.py migration file. It will be included in 0.4.7.
I will release it after having closed #22

**Comment by fabiocaccamo** [comment]
@alcfernandes you can now upgrade to `0.5.0` version.

**Comment by alcfernandes** [comment]
@fabiocaccamo, I did upgrade and everything is working fine now. Thank you very much!
