### ISSUE TITLE
tabbed fieldsets in another language

### ISSUE THREAD

**Issue by rikengct** [fabiocaccamo/django-admin-interface#253]
I love the tabbed fieldsets in the latest version.
but, i noticed that if I switch to another language (japanese in this case), the are no longer linked.
For example, for my tabbed fieldset with label 'Field', the url is admin/app/model/pk/change/#Field
but, when i switch the language, it always reverts to admin/app/model/pk/change/# if I have defined the label for that tab in my django.po file. Without being able to have the tabs functional when labeling the tabs in Japanese, I am forced to use the old layout.

**Comment by fabiocaccamo** [comment]
@rikengct thank you for reporting this. 
I close it because it's a duplicate of #237
