### ISSUE TITLE
Login page needs title background colour

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#259]
**Django version**: 4.1.6

**Package version**: 0.24.2

**Current behavior (bug description)**
The parameter `title_color` is used on the login page and the banner section of other pages.
If the banner background is dark (like in the USDS or Foundation theme, the one that’s blue and grey) and the title colour white, it looks good on the banner and can’t be seen on the white background on the login page.

**Expected behavior**
Ability to set `background_color` for the login page (section `Title` if I’m not mistaken)

Or/and separate two variables to control `title_color` on title screen and pages banner.

**Comment by fabiocaccamo** [comment]
@merwok the title is always inside the header, so the color contrast problem should be the same in the login page and in the dashboard page, could you attach a couple of screenshots of how you see the title in both pages please?

**Comment by merwok** [comment]
No, on the login page there isn’t a header, so my light blue colour looks great on normal pages with grey background but is hard to see on login page with white background!

**Comment by merwok** [comment]
I absolutely did!  Copied from django and customized for logo position and a couple other things.

I will compare with/without my override and see what class I’m missing to apply banner colour background to the top rectangle of the login form zone.  Thanks for the help!
