### ISSUE TITLE
Logo not showing in admin panel

### ISSUE THREAD

**Issue by ivan-masiuk** [fabiocaccamo/django-admin-interface#261]
**Python version**
3.11

**Django version**
4.0.1

**Package version**
0.24.2

I installed by tutorial package, updated settings and so on, added logo image, but if I open admin panel logo shows for 1–2 seconds and that's it.

In the code, I found style in this image and if I delete it — image is showing OK.

**Comment by merwok** [comment]
Can you explain what you mean by «open admin panel» ?

**Comment by ivan-masiuk** [comment]
> Can you explain what you mean by «open admin panel» ?

Yes, sure! I mean django-admin panel, that by default we can find at /admin url

Additionally linkt to the off. docs: [https://docs.djangoproject.com/en/4.1/ref/contrib/admin/](DOCS)

**Comment by fabiocaccamo** [comment]
@ivan-masiuk could you share the logo you are using please?

**Comment by ivan-masiuk** [comment]
@fabiocaccamo 
![test](https://user-images.githubusercontent.com/45178554/219934957-e8f3684f-d298-4f22-b69f-ca88b0c64254.png)

This is how any logo is displayed, but here is an example of mine

**Comment by ivan-masiuk** [comment]
@fabiocaccamo 

Also, I created video for you with bug: https://youtu.be/cDUeq1d63H4

**Comment by fabiocaccamo** [comment]
@ivan-masiuk thank you! 

It's very strange that it disappear after few time, considering also that there is not js involved there. 

Is it an .svg file? 
If yes, are there width, height and viewbox attributes?

**Comment by ivan-masiuk** [comment]
@fabiocaccamo 

No, it's .png file (but I also used others types, but result was the same)

Maybe I have local any problems with settings or smth?

**Comment by fabiocaccamo** [comment]
Is there any error in the console?

**Comment by ivan-masiuk** [comment]
For /admin path:

`[19/Feb/2023 09:50:13] "GET /admin/ HTTP/1.1" 200 26528
[19/Feb/2023 09:50:13] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[19/Feb/2023 09:50:13] "GET /media/admin-interface/logo/test_BtQVGQa.png HTTP/1.1" 304 0
[19/Feb/2023 09:50:13] "GET /media/admin-interface/favicon/test.png HTTP/1.1" 304 0
[19/Feb/2023 09:50:13] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[19/Feb/2023 09:50:13] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0`

**Comment by fabiocaccamo** [comment]
Have tried with another browser / clear the cache?

**Comment by ivan-masiuk** [comment]
Hmmm, in Safari works good. But in Chrome, after clearing the cache, the problem still exists.

May I close issue?

**Comment by fabiocaccamo** [comment]
Last attempt, could you try to disable all your browser extensions and retry please?

**Comment by fabiocaccamo** [comment]
@dancaron what is the value of your `STATIC_URL` setting?

**Comment by dancaron** [comment]
```STATIC_URL = "/static/" # /static in dev and STATIC_ROOT in prod```

**Comment by ivan-masiuk** [comment]
Guys, I don't know how, but in one prod it's works OK, in other -- nOK.

Also, if I shut down extensions (incognito page) — works OK.

**Comment by dancaron** [comment]
@ivan-masiuk Can you post the url to the logo in each environment?

**Comment by ivan-masiuk** [comment]
@dancaron 
Sorry. NDA prods :(

**Comment by ivan-masiuk** [comment]
Yep. I think we have a problem with version OR with js in extensions (maybe extensions think that that image is ads/spam)

**Comment by fabiocaccamo** [comment]
If it works correctly by disabling extensions the answer is 101% there.

**Comment by ivan-masiuk** [comment]
Probably not. 

Why in one prod it works with extensions and in another—no?

UPD. I close all extensions in prod1, but logo in not show

**Comment by ivan-masiuk** [comment]
@dancaron I checked urls to the logos, they are same.

Problem is not in url or static settings

**Comment by dancaron** [comment]
I have all extensions disabled. Still not working.

**Comment by fabiocaccamo** [comment]
The logo is there but hidden by CSS?

**Comment by dancaron** [comment]
@fabiocaccamo I checked that. No, seems browser is applying that rule when image url is 404.

**Comment by dancaron** [comment]
I have another instance of django admin interface on another site, and using same Chrome profile, works fine.

**Comment by dancaron** [comment]
Perhaps {% load static %} isn't being called somewhere?

**Comment by fabiocaccamo** [comment]
Sorry, I messed up, the logo is not a static image, have you set your `MEDIA_URL` setting correctly?

Here you can see how the logo is displayed, nothing special: https://github.com/fabiocaccamo/django-admin-interface/blob/main/admin_interface/templates/admin/base_site.html#L160

**Comment by dancaron** [comment]
Yes, setting MEDIA_ROOT, and removing and adding logo again fixed the problem. :)

**Comment by Instrumedley** [comment]
if I can add one more comment to the solution provided by @dancaron , don't forget to add 'media' url entry in your project urlpatterns in the urls.py :

<code>
from django.conf.urls.static import static
from django.conf import settings

...
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
</code>
