### ISSUE TITLE
Feature request: specify favicon

### ISSUE THREAD

**Issue by JakobGM** [fabiocaccamo/django-admin-interface#28]
It would be nice if it was possible to specify the favicon of the admin interface without extending any template.

Thanks,
Jakob

**Comment by fabiocaccamo** [comment]
Sure, this feature will be available soon. There are 2 possibilities: add support for the old classic favicon file (16x16 / 32x32) or add support for all icons actually supported by different platforms (check http://www.favicomatic.com).
The second approach would be more complete and there are some django libs doing this job well so an integration with these libs would be the best choice.

**Comment by JakobGM** [comment]
Great!

I have used [a similar service](http://www.favicon-generator.org) before. Just uploading a single high-res version of a favicon, and then letting the app generate the rest would be awesome.

But personally I would be more than satisfied by just having basic favicon support. 😄 

By the way,
Thanks for a great app!

**Comment by fabiocaccamo** [comment]
You are right, a simple favicon is better than nothing. 😄

Thank you Jakob!!

**Comment by fabiocaccamo** [comment]
@JakobGM favicon support available with `0.5.2` version

**Comment by JakobGM** [comment]
Great, thanks a lot, @fabiocaccamo!
