### ISSUE TITLE
Confusing warnings on `./manage.py collectstatic`

### ISSUE THREAD

**Issue by helgihg** [fabiocaccamo/django-admin-interface#283]
**Python version**
3.9.2

**Django version**
4.2.0

**Package version**
0.25.0

**Current behavior (bug description)**
When running `./manage.py collectstatic`, a warning is produced:

```
Found another file with the destination path 'admin/js/cancel.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/popup_response.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/collapse.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
```

These are presumably naming conflicts with `django.contrib.admin`.

Warnings such as these have a tendency to waste time for developers/admins, because the impact is entirely unclear, and when developers/admins (especially those who did not integrate `django_admin_interface` themselves) run into them in a scenario where there is some **unrelated** problem with static files or the admin interface, it runs them down a rabbit hole for no good reason.

**Expected behavior**
Running `./manage.py collectstatic` should not produce the aforementioned warnings.

**Comment by fabiocaccamo** [comment]
@helgihg unfortunately these logs are from the collectstatic command and there is no way to silence them, there is also an issue [here](https://code.djangoproject.com/ticket/26583).

I will add a note to the README to inform users about the warnings in advance.

If you find a way to silence these warnings I will re-open the issue.
