### ISSUE TITLE
Add image uploader widget 

### ISSUE THREAD

**Issue by offbrok** [fabiocaccamo/django-admin-interface#284]
Consider integrating this solution: https://github.com/inventare/django-image-uploader-widget

<a href="https://dashboard.polar.sh/fabiocaccamo/django-admin-interface/issues/284">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/284/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/284/pledge.svg">
</picture>
</a>

**Comment by offbrok** [comment]
Replace the standard image download widget. And also replace the loading of linked images (inline).

I am not suggesting this particular solution.
It is possible to use your solution, but I think it was cool to change the widget download files, images, etc. As it fits into the concept of your package.

**Comment by fabiocaccamo** [comment]
@offbrok frankly this widget doesn't impress me at all.

I keep this issue open because I like the idea, but I would like a widget that improves the default one with the following features:
- [ ] automatic previewing
- [ ] manual resizing
- [ ] manual cropping

**Comment by offbrok** [comment]
> @offbrok frankly this widget doesn't impress me at all.
> 
> I keep this issue open because I like the idea, but I would like a widget that improves the default one with the following features:
> 
> * [ ]  automatic previewing
> * [ ]  manual resizing
> * [ ]  manual cropping

Yes, I like your idea of a widget.

**Comment by fabiocaccamo** [comment]
@offbrok I close this because I don't think that I will ever implement it.
