### ISSUE TITLE
Custom base_site.html

### ISSUE THREAD

**Issue by raratiru** [fabiocaccamo/django-admin-interface#29]
Thank you for this awesome KISS plugin! 

I have a custom base_site.html, how can I make it work?

**Comment by raratiru** [comment]
A solution I have found is [django-apptemplates](https://github.com/bittner/django-apptemplates).

Then, in my `base_site.html`, I added:

`{% extends "admin_interface:admin/base_site.html" %}`

Works great.

**Comment by fabiocaccamo** [comment]
@raratiru I will add it to README. Thanks

**Comment by fabiocaccamo** [comment]
https://github.com/fabiocaccamo/django-admin-interface/blob/master/README.md#faq

**Comment by raratiru** [comment]
Awesome, thank you!
