### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by alb3rto** [fabiocaccamo/django-admin-interface#3]
Hi,
In django 1.9 the admin theme was updated. This project support django 1.9? If not, do you plan to include support soon?

**Comment by fabiocaccamo** [comment]
Actually the project has not been tested on Django 1.9 (I'm working with 1.8).
django-admin-interface uses the same base theme of Django 1.9 (as an external dependency) and as a plus lets you customize the theme appereance.

**Comment by alb3rto** [comment]
I tried to use it directly with django 1.9 (just removing the 'flat' dependency) and got a `AppRegistryNotReady` exception. If I have some free time and there is not any PR yet, I will try to solve it.

**Comment by fabiocaccamo** [comment]
In any case, since there is not much python code it will be easy to make it compatible with Django 1.9.

**Comment by maxiplux** [comment]
hi my friend , thank you very much for you project , but do you have any idea to fix the problem on django 1.9 , i like your project is amazing . thanks

**Comment by fabiocaccamo** [comment]
Hi @maxiplux , 
actually all my open projects are on Django 1.8.*, when I will have some free time I will test and fix for Django 1.9. In any case it's open source, feel free to fix it and send me a PR.

**Comment by fabiocaccamo** [comment]
Hi @maxiplux  and @alb3rto , 
Please check `0.1.4` version for **Django 1.9 support**.
If you like this project share it, I think that few people know about it...

**Comment by paolodina** [comment]
I confirm it works well with Django 1.9.2. Thanks for the very nice project.

**Comment by paolodina** [comment]
Btw, I forgot to say that the homepage says Python 2.6, Python 2.7 as requirements, but I tried it in Python 3.4.3 and works fine.

**Comment by fabiocaccamo** [comment]
I update the readme.

**Comment by maxiplux** [comment]
my friend , thak you ver much for your amazing job , it's wonderful .

**Comment by maxiplux** [comment]
one comment , the messages of the framework messages of django admin , would be possible set the css for it ?

**Comment by fabiocaccamo** [comment]
Actually, the messages style is not overridden, but potentially any css could be changed...
