### ISSUE TITLE
Related Modal not working when Clickjacking Protection is enabled

### ISSUE THREAD

**Issue by raratiru** [fabiocaccamo/django-admin-interface#30]
When `django.middleware.clickjacking.XFrameOptionsMiddleware` [is used](https://docs.djangoproject.com/en/dev/ref/clickjacking/) the modal is blocked and never shows up.

I had to disable the header for the admin pages in order to make it work, although the default setting is `SAMEORIGIN`.

> By default, the middleware will set the X-Frame-Options header to SAMEORIGIN for every outgoing HttpResponse.

**Comment by fabiocaccamo** [comment]
I use `django.middleware.clickjacking.XFrameOptionsMiddleware` but I can't reproduce this issue.

**Comment by raratiru** [comment]
You are right ... I have a rather complicated setup and I have not tried to reproduce it in a fresh install of Django. 

However, these are the versions of the applications I would consider relative:

Python 3.5.4
Django 1.11.9
django-admin-interface 0.5.9
django-admin-shortcuts 1.2.7
django-flat-responsive 2.0
django-flat-theme 1.1.4
django-tabbed-admin 1.0.3
django-apptemplates 1.4
django-decorator-include 1.3

I have also overridden the following files (using [django-app-templates](https://github.com/shlomozippel/django-apptemplates))as such (I am overriding different files from different applications, I wonder if this could be the cause of the issue):

base_site.html: 

```
{% extends "admin_interface:admin/base_site.html" %}
...

```

index.html:

```
{% extends "admin:admin/index.html" %}
...

```

I have debuged it using the Developper's Web Console of Firefox 52.5.2, where I saw the related message.

In order to deactivate `jango.middleware.clickjacking.XFrameOptionsMiddleware` I used [django-decorator-include](https://github.com/twidi/django-decorator-include) and added the following to my urls.conf:

```
from django.views.decorators.clickjacking import xframe_options_exempt
from decorator_include import decorator_include

    urlpatterns = (
        ...
        url(r'^admin/', decorator_include(xframe_options_exempt, admin.site.urls)),
        ....
    )
```

**Comment by fabiocaccamo** [comment]
Ok, could you try to don't override the admin templates and re-activate `django.middleware.clickjacking.XFrameOptionsMiddleware`?

**Comment by raratiru** [comment]
I disabled `django-admin-shortcuts`, deleted the overridden files `base_site.html` and `index.html` but the issue still remains:

> Load denied by X-Frame-Options: https://<path-to-my-app>/add/?_to_field=id&_popup=1&_modal=939156 does not permit framing.

**Comment by fabiocaccamo** [comment]
Could you check if you have in your nginx conf add_header X-Frame-Options DENY; and eventually comment it.

**Comment by fabiocaccamo** [comment]
Could you check also if you have `X_FRAME_OPTIONS = 'DENY'` in your `settings.py`? If you have it, comment it...

**Comment by raratiru** [comment]
Whoaaa! 

You are very right:  `nginx.conf` ! 🥇 

Thank you!
