### ISSUE TITLE
Change font in rtl

### ISSUE THREAD

**Issue by kheiripour** [fabiocaccamo/django-admin-interface#305]
**Python version**
3.11

**Django version**
4.2

**Package version**
0.26

**Current behavior (bug description)**
I cant change font for rtl by modifying base_site.html and making an override css file.
After many surveys I found that it is because in rtl.css file line 2 there is an !important on font-family:

[dir="rtl"] .admin-interface * {
    font-family: 'Vazir', sans-serif !important;
}

so my override css file font will ignore.

**Expected behavior**
I expect that can modify font-family on my own css files. 
So it seems that ! important should remove.
Thank you for your awesome package.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/305">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/305/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/305/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@kheiripour RTL support has been added by @theSinner in #98.

@theSinner do you remember why you added `!important` to the font-family css declaration? 
Could you check please if removing `!important` as requested by @kheiripour breaks something?

**Comment by fabiocaccamo** [comment]
@kheiripour anyway... have you considered to override it using a stronger css selector?

```css
[dir="rtl"] body.admin-interface * {
    font-family: 'Your-Font', sans-serif !important;
}
```

**Comment by fabiocaccamo** [comment]
> @kheiripour anyway... have you considered to override it using a stronger CSS selector?
> 
> ```css
> [dir="rtl"] body.admin-interface * {
>     font-family: 'Your-Font', sans-serif !important;
> }
> ```

Since this workaround works perfectly I close this issue.

**Comment by kheiripour** [comment]
> > @kheiripour anyway... have you considered to override it using a stronger CSS selector?
> > ```css
> > [dir="rtl"] body.admin-interface * {
> >     font-family: 'Your-Font', sans-serif !important;
> > }
> > ```
> 
> Since this workaround works perfectly I close this issue.

Yes, I solve this problem by adding CSS file to  override rtl font. Actually this problem force me to make this overriding CSS file for admin-interface.
