### ISSUE TITLE
Update Spanish translations

### ISSUE THREAD

**Issue by smunoz-ml** [fabiocaccamo/django-admin-interface#306]
Some Spanish translations are not up to date and text in English is shown

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/306">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/306/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/306/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
Thank you for the PR
