### ISSUE TITLE
Form for each fieldsets

### ISSUE THREAD

**Issue by zN3utr4l** [fabiocaccamo/django-admin-interface#308]
**Python version**
3.9

**Django version**
3.2.20

**Package version**
0.26.0

**Current behavior (bug description)**
I'm trying to add a form for each **fieldsets as tab**, only if passed a bool, I changed the change_form.html file like this.
```
{% if show_fieldsets_as_tabs %}
            {% for fieldset in adminform %}
            {% with fieldset.name|default_if_none:opts.verbose_name as tab_name %}
            {% if shop_custom %}
                <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}{% if form_url %}action="{{ form_url }}" {% endif %}method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
            {% endif %}
            <div id="tabcontent-{{ tab_name|admin_interface_slugify }}" class="tabbed-changeform-tabcontent {{ forloop.counter0|default:'active' }}">
                {% include "admin/includes/headerless_fieldset.html" %}
            </div>
            {% if shop_custom %}
                </form>
            {% endif %}
            {% endwith %}
            {% endfor %}
        {% else %}
```

There are 5 tabs, the first 4 have loot defined in fieldsets the last one doesn't:
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/214b9efa-3401-4caa-91c5-12ba49246b6a)
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/7462db1b-17b3-46f9-a4fa-510a8b34a6b6)

**Expected behavior**
The problem is that it creates the form in all tabs except the first one, but it creates the csrf token, which means it enters the if, but it fails to create the form I don't know why.
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/74bdc9b3-d79e-470e-a822-dd6a78b680ea)

Is this issue related to the django-admin-interface library? somehow, when it goes to create the active tab it goes to delete something?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/308">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/308/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/308/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@zN3utr4l could you try please to disable the tabbed fieldset option to check if the problem is present even with the default fieldset?

**Comment by zN3utr4l** [comment]
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/8bd35d22-de60-4bfb-9a19-35e5f8e540bb)

even without the tabbed fieldset the first fieldset block has no form, maybe it's a django related error?

**Comment by fabiocaccamo** [comment]
@zN3utr4l if the problem persists even without the tabbed subset there are two possibilities:
- you are doing something wrong
- it's a django related error

Maybe you can try to reduce what you are doing to a minimal test to understand the cause.

**Comment by zN3utr4l** [comment]
> Maybe you can try to reduce what you are doing to a minimal test to understand the cause

# admin.py
```
readonly_fields = ('test_btn', 'test_btn2')
fieldsets = (
    ('test', {
        'classes': ('collapse', 'expanded'),
        'fields': ('test_btn',)
    }),
    ('test2', {
        'classes': ('collapse', 'expanded'),
        'fields': ('test_btn2',)
    })
)

def test_btn(self, obj):
    return format_html('<input type="submit" value="test_btn" name="_test_btn">')

def test_btn2(self, obj):
    return format_html('<input type="submit" value="test_btn2" name="_test_btn2">')
```

# templates/admin/includes/[fieldset.html](https://github.com/django/django/blob/main/django/contrib/admin/templates/admin/includes/fieldset.html)

wrap all code in:

```
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}{% if form_url %}action="{{ form_url }}" {% endif %}method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}

</form>
```


# if show_fieldsets_as_tabs templates/admin/change_form.html

wrap this code:
```
<div id="tabcontent-{{ tab_name|admin_interface_slugify }}" class="tabbed-changeform-tabcontent {{ forloop.counter0|default:'active' }}">
    {% include "admin/includes/headerless_fieldset.html" %}
</div>
```

**Comment by fabiocaccamo** [comment]
The problem is that `{% block form_top %}{% endblock %}` is rendered empty only for the last fieldset right?

**Comment by zN3utr4l** [comment]
No, the problem is the first fieldset, only `{% csrf_token %}` is rendered

Good:
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/f6ef65ce-d214-4a50-aa3b-1963d32f04cd)

Not Good:
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/edc6bf45-82fc-47a7-b568-8c7669682346)

From this image you can see all fieldsets enclosed in the form except the first one
![image](https://github.com/fabiocaccamo/django-admin-interface/assets/73225008/8bd35d22-de60-4bfb-9a19-35e5f8e540bb)

**Comment by fabiocaccamo** [comment]
If you remove "admin_interface" from the installed apps, does this problem persists?

**Comment by zN3utr4l** [comment]
the error persists, it seems to be a django error
