### ISSUE TITLE
Unicode Characters Not Slugified Properly in Inlines Tabs

### ISSUE THREAD

**Issue by design-vs** [fabiocaccamo/django-admin-interface#322]
**Python version**
3.8

**Django version**
4.1.3

**Package version**
0.24.2

## **Current behavior (bug description)**
When the admin interface language is set to non-Latin languages (e.g., Greek), the slugify template filter does not work correctly, leading to the inlines tabs malfunctioning.

Specifically, the generated HTML for the inlines tabs buttons does not slugify non-Latin characters correctly. This results in buttons not having a proper id attribute and the associated onclick event fails to switch between tabs. Note: Django's slugify returns an empty string for non-Latin characters.

Here's how the problematic HTML looks:

```
<button type="button" id="tablink-" class="tabbed-changeform-tablink" onclick="AdminInterface.tabbedChangeForm.openTab(event, '')">
    Ιδιότητες πόρτας
</button>
```

## **Expected behavior**
The inlines tabs should work correctly in all languages. The slugify filter should produce a valid slug for non-Latin characters, allowing the tabs to function properly.

For example, the HTML for the inlines tabs in Greek should look something like:

```
<button type="button" id="tablink-ιδιότητες-πόρτας" class="tabbed-changeform-tablink" onclick="AdminInterface.tabbedChangeForm.openTab(event, 'ιδιότητες-πόρτας')">
    Ιδιότητες πόρτας
</button>
```

or

```
<button type="button" id="tablink-idiotetes-portas" class="tabbed-changeform-tablink" onclick="AdminInterface.tabbedChangeForm.openTab(event, 'idiotetes-portas')">
    Ιδιότητες πόρτας
</button>
```

## **Suggested Solutions**

1. Create a custom slugify filter in the `admin_interface_tags.py` using Django's built-in slugify with the `allow_unicode` parameter:

```
@register.filter(name='unicode_slugify')
def unicode_slugify(value):
    return slugify(value, allow_unicode=True)
```

Replace all `slugify` filter calls in the `change_form.html` template with the `unicode_slugify` filter.

2. Alternatively, we can use the `unidecode` library to convert non-ascii to ascii so the IDs will be in Latin characters:

```
@register.filter(name='unicode_slugify')
def unicode_slugify(value):
    return slugify(unidecode(value))
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/322">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/322/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/322/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@design-vs this has [already been fixed](https://github.com/fabiocaccamo/django-admin-interface/blob/main/CHANGELOG.md#0250---2023-04-18), please upgrade to the latest version.
