### ISSUE TITLE
Language chooser is broken with `prefix_default_language=False`

### ISSUE THREAD

**Issue by julianwachholz** [fabiocaccamo/django-admin-interface#327]
**Django version**
1.9 and up

**Current behavior (bug description)**
- In a Django project with `i18n_patterns(..., prefix_default_language=False)` the language  picker will not be shown unless the user is already on a non-default language. 
- When using the language chooser to go back to the default language, it gets hidden.

**Expected behavior**
- Language chooser should work the same as with with `prefix_default_language=True`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/327">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/327/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/327/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@julianwachholz thank you for reporting this issue!

**Comment by fabiocaccamo** [comment]
You can upgrade to `0.27.0` version, thanks again for the PR!
