### ISSUE TITLE
Form fields sizing and layout

### ISSUE THREAD

**Issue by nyejon** [fabiocaccamo/django-admin-interface#33]
It would be nice if it was possible to customise the form field sizing and layout.

For example to autosize the fields based upon the fieldsets definition so everything looks neat and aligned. Is there a way to do this already?

**Comment by nyejon** [comment]
For example: if I have the fieldsets like:

(Field1, Field2)
(Field3, Field4)
(Field5, Field6, Field7)
(Field8)

It would produce the layout as:

![image](https://user-images.githubusercontent.com/17871768/36530331-153715aa-17bb-11e8-8e77-53209ac3687d.png)

At the moment all of the fields with different types are different sizes etc so the layout when using fieldsets can look wonky as each field is a different size.

**Comment by fabiocaccamo** [comment]
Thanks, I understand now. 
Frankly I never had this problem because I never use more fields on the same line.
I think it is hard to handle all cases, just think to custom widgets...

**Comment by nyejon** [comment]
Ok, so there is no way to add something like 'form-control' from bootstrap or similar? Kinda like the example:

http://getbootstrap.com/docs/4.0/components/forms/#form-row

Sorry, I'm not familiar with how the django admin lays things out and what would be involved to make it look a bit nicer... but without changing much. The other admin packages change so much and what I like about this one is it is basically default but adds a few nice things.

**Comment by fabiocaccamo** [comment]
The main purpose of this library is to improve the default django admin by offering customization and some other features.

Your needs are more related to the base style offered by `django-flat-theme`, so if you want to ask some improvements to it you should open an issue [here](https://github.com/elky/django-flat-theme).
