### ISSUE TITLE
Filter Input Fields collapsing on different layouts

### ISSUE THREAD

**Issue by AlexR130** [fabiocaccamo/django-admin-interface#338]
**Python version**
3.12.0

**Django version**
4.2.8

**Package version**
0.27.0

**Current behavior (bug description)**
I'm not quite sure if this is acually a bug but it looks to me as that this is not an expected behavior. If you have a selector list ro put elements from the right to the left side there will be 2 filter input fields. Depending on the layout size the responsed layout looks as expected or not.

If your layout is slightly wider then half the screen it appears like in the sceenshot below):
![chrome_PzqX3Ca3KT](https://github.com/fabiocaccamo/django-admin-interface/assets/154223252/dd35be42-ccd6-4761-a923-9ec50f86f345)

on half the screen or a bit smaller it appears like in the screenshot below (also the add-button (the +) moves on top of the list (is this an expected behavior?)):
![chrome_ShWBr3lKn4](https://github.com/fabiocaccamo/django-admin-interface/assets/154223252/85db93ca-8141-4c45-9c54-d9cc59feec2a)

**Expected behavior**
shown in the screenshot below:
![chrome_lm0A8poKLf](https://github.com/fabiocaccamo/django-admin-interface/assets/154223252/f8b63e45-bca6-42f8-bc54-c9356ab84767)

I found out that if you disable the min width of the lable it works as I would expect it. In the screenshot below is what I have found:
![chrome_4Tv0YdN0wk](https://github.com/fabiocaccamo/django-admin-interface/assets/154223252/2f662b44-1c28-43e9-8214-79a3ea10c451)

the source file: 
![chrome_mXJCTodPhC](https://github.com/fabiocaccamo/django-admin-interface/assets/154223252/780c972e-ae4d-4e44-a378-4e5d3dca95bb)

If there is any already existing solution for this I apologize this post but i could find anyhting.

Thanks in advance for any response 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/338">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/338/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/338/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@AlexR130 fixed in `0.28.0` version.
