### ISSUE TITLE
Adding Support for `django-rosetta` Package

### ISSUE THREAD

**Issue by Farhaduneci** [fabiocaccamo/django-admin-interface#340]
Hey there,
Thanks so much for all your work on this repo! I really appreciate you contributing to Django.

I would like to propose the addition of support for the [django-rosetta](https://github.com/mbi/django-rosetta) package. I use this package alongside your project and inconsistent themes are kinda buggy.

I understand that adding support for new packages requires careful consideration and effort. I would be grateful if you could share some insight into the general process you follow when considering adding support for new packages. This information would be incredibly valuable as I am interested in contributing to the project and would like to understand how I could potentially assist in implementing this feature.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/340">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/340/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/340/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@Farhaduneci thank you for this suggestion, personally I don't use `django-rosetta`, so I don't think I will ever work on this issue until I will need it personally for a commercial project or this package will have some sponsors, but if you want to contribute feel free to submit a PR, I will be glad to review and merge it.

More generally regarding third-party packages support, it quite impossible to support all the most popular admin packages and maintaining them well supported along the time.

I think that it would be nice if third-party packages would start to use some CSS rules prefixed by `.admin-interface` selector (so they will do nothing if this package is not used) in combination with [CSS variables exposed by this package](https://github.com/fabiocaccamo/django-admin-interface#add-more-themes) to improve their appereance when this package is used.
