### ISSUE TITLE
TemplateDoesNotExist with use django-nested-admin

### ISSUE THREAD

**Issue by markdrrr** [fabiocaccamo/django-admin-interface#341]
**Python version**
3.11

**Django version**
4.2

**Package version**
django-admin-interface==0.28.0

**Current behavior (bug description)**
In my project, I use **django-nested-admin==4.0.2** and I get an error:
_TemplateDoesNotExist nesting/admin/inlines/headerless_tabular.html_
Most likely the problem is in the method **get_admin_interface_inline_template**
incorrectly processes the path

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/341">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/341/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/341/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@markdrrr thank you for reporting this issue, if you can submit a PR it would be great!

**Comment by fabiocaccamo** [comment]
@markdrrr thank you very much for the PR, you can upgrade to `0.28.1` version.
