### ISSUE TITLE
Bug in display of related links with autocomplete fields

### ISSUE THREAD

**Issue by gersmann** [fabiocaccamo/django-admin-interface#348]
**Python version**
3.12

**Django version**
4.2

**Package version**
0.28.1

**Current behavior (bug description)**
After updating from 0.27.0 to 0.28.1 we are experiencing a layout issue in the related object links:
<img width="521" alt="image" src="https://github.com/fabiocaccamo/django-admin-interface/assets/2694872/49986bff-d542-4c37-851d-fd7a062aef76">

**Expected behavior**
Standard Layout

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/348">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/348/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/348/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@gersmann have you run `python manage.py collectstatic` after having updated this library?

The latest version has been optimized for `django 5.0', so if the problem persists, please consider to rollback to the prev version.

**Comment by gersmann** [comment]
> @gersmann have you run `python manage.py collectstatic` after having updated this library?
> 
> The latest version has been optimized for `django 5.0', so if the problem persists, please consider to rollback to the prev version.

Makes sense, thank you. We'll update soon, currently waiting for a plugin to release their Django 5 compat. I'll leave this open for visibility, but feel free to close anytime.

**Comment by gersmann** [comment]
About collectstatic, yes, we've done that.

**Comment by fabiocaccamo** [comment]
@gersmann fixed in `0.28.2` version.

**Comment by gersmann** [comment]
Thx :)
