### ISSUE TITLE
The default View Site link not showing in the mobile version

### ISSUE THREAD

**Issue by ashalaby** [fabiocaccamo/django-admin-interface#358]
**Python version**
3.11

**Django version**
5.0

**Package version**
0.28.0

**Current behavior (bug description)**
When access the Django Admin page, the default 'View Site' which is showing in the desktop version, does not show on mobile devices.

**Expected behavior**
Default menu items '[VIEW SITE]/ [CHANGE PASSWORD] /  LOG OUT should show up on mobile version

**Comment by fabiocaccamo** [comment]
@ashalaby I don't have this issue on my active projects and I'm not able to reproduce it.
