### ISSUE TITLE
Popup window freezes in Chrome after save

### ISSUE THREAD

**Issue by karlkvist** [fabiocaccamo/django-admin-interface#359]
**Python version**
3.11.7

**Django version**
4.2.9

**Current behavior (bug description)**
I encountered abnormal behavior in the Chrome browser (latest version) when opening a popup window in the Django-admin interface and clicking on the Save button, all the windows of a Chrome instance freeze, forcing me to close and reopen Chrome. I see a blank window with the title 'Chiusura popup' until Chrome asks if I want to wait for the response or forcefully close the window. Everything works fine in Firefox.  I am attaching some screenshots.

![Screenshot 2024-01-30 at 09 50 17](https://github.com/fabiocaccamo/django-admin-interface/assets/15107211/b3593409-a42c-4c4b-96b0-d9627c47704f)
![Screenshot 2024-01-30 at 09 51 21](https://github.com/fabiocaccamo/django-admin-interface/assets/15107211/a9c1ad77-a1e3-4502-b110-59478f1a9cd9)

Last server requests/responses:
![Screenshot 2024-01-30 at 10 07 43](https://github.com/fabiocaccamo/django-admin-interface/assets/15107211/34f7a66d-6a40-4fe1-8783-7c82b605fe65)

**Expected behavior**
The popup window should be closed

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/359">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/359/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/359/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@karlkvist I'm not able to replicate this, could you try please with an anonymous window and without extensions?

**Comment by fabiocaccamo** [comment]
@merwok could you check if you too are experiencing this error? ...otherwise I will close the issue as it is invalid.

**Comment by merwok** [comment]
No issue with Chromium 121 and django-admin-interface 0.26.0

**Comment by fabiocaccamo** [comment]
@merwok thank you very much!
