### ISSUE TITLE
"pencil" icon not working

### ISSUE THREAD

**Issue by heiqs** [fabiocaccamo/django-admin-interface#36]
Hi,
After adding django-admin-interface to the installed_apps, nothing happens when I click the "pencil" and "add" icons in a change form of django admin.

Django version is 1.11 and python 2.7

Thanks for help.

**Comment by fabiocaccamo** [comment]
Have you followed step-by-step the installation instructions?

**Comment by fabiocaccamo** [comment]
@heiqs any update?

**Comment by fabiocaccamo** [comment]
@heiqs if you don't contribute I will close this issue.

**Comment by heiqs** [comment]
Hi Fabio,

So sorry. Was busy with some private issues. I will update the issue soon.

Cheers,
Mohammad
