### ISSUE TITLE
Use modal for search dialog of raw_id_fields, too

### ISSUE THREAD

**Issue by djpretzel** [fabiocaccamo/django-admin-interface#37]
- modal for add/edit and other popups is very nice
- currently the popup to search records for raw_id_fields widget (opened via the magnifying glass icon) still uses the old popup
- it would be rad if it worked the same way!

**Comment by fabiocaccamo** [comment]
@djpretzel thanks for the report, I will fix it as soon as possible.

**Comment by fabiocaccamo** [comment]
You can install `0.7.0` version to use this feature.
