### ISSUE TITLE
Django admin date_hierarchy linking is not working anymore

### ISSUE THREAD

**Issue by jeroenpeters1986** [fabiocaccamo/django-admin-interface#374]
**Python version**
3.11

**Django version**
5.0.2

**Package version**
0.28.5

**Current behavior (bug description)**
I am using the "date_hierarchy" (https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.date_hierarchy) function on a Django model. With version 0.28.5 I am getting this error when I click on the Year
```
TypeError at /nl/admin/budgie_bird/bird/
int() argument must be a string, a bytes-like object or a real number, not 'list'
Request Method:	GET
Request URL:	https://pybudgie.ddev.site/nl/admin/budgie_bird/bird/?date_of_birth__year=2020
Django Version:	5.0.2
Exception Type:	TypeError
Exception Value:	
int() argument must be a string, a bytes-like object or a real number, not 'list'
Exception Location:	/var/www/html/.ddev/.venv/lib/python3.11/site-packages/admin_interface/templatetags/admin_interface_tags.py, line 147, in admin_interface_date_hierarchy_removal_link
Raised during:	django.contrib.admin.options.changelist_view
```

**Expected behavior**
It seems that the received params have changes and are now a list instead of the string from the URL

I will submit a PR, I am not sure if this is because of Django5 or earlier

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/374">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/374/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/374/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@jeroenpeters1986 thank you for having reported this issue!

The error is raised [here](https://github.com/fabiocaccamo/django-admin-interface/blob/main/admin_interface/templatetags/admin_interface_tags.py#L147), so I'm pretty sure it's an issue related with the latest django version.

If you can submit a PR with a backward-compatible fix that would be great!

**Comment by jeroenpeters1986** [comment]
Hi @fabiocaccamo I will edit my PR tomorrow so that it will work on both versions :-)

**Comment by fabiocaccamo** [comment]
@jeroenpeters1986 yes, I saw that it doesn't pass the tests...

**Comment by jeroenpeters1986** [comment]
Yes to honest I checked out the bug and fixed it locally, and with the diff I created the PR, not realizing you have other mechanism around it until I created the PR. So I need a bit of time but will check it out tomorrow (maybe Friday) and I will update it and let you know when I think it’s ready hahaOp 7 mrt 2024 om 00:38 heeft Fabio Caccamo ***@***.***> het volgende geschreven:﻿
@jeroenpeters1986 yes, I saw that it doesn't pass the tests...

**Comment by fabiocaccamo** [comment]
@jeroenpeters1986 thanks for the PR, you can upgrade to `0.28.6` version.

**Comment by jeroenpeters1986** [comment]
Thanks so much! I will upgrade it tonight. Thanks so much for the awesome package, glad I could do something 'back'
