### ISSUE TITLE
Logo image not showing

### ISSUE THREAD

**Issue by manoantares2** [fabiocaccamo/django-admin-interface#38]
I'm new to django, I installed and applied the USWSD theme on my site, but the logo image is not showing and when i enter the editing page for the theme and click on the link for the logo, this error mesage shows up: "Theme with ID "3/change/admin-interface/logo/akua%b65YP.gif" doesn't exist. Perhaps it was deleted?", i tried to change the static folder to various locations on the settings.py but nothing worked to make the image show u, is there a limit to the size of th logo or a restriction about its format? my logo file is a .gif with  64x47 size and weights 4kb.

my settings.py looks like this (the static related stuff is at the bottom):

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = 'spam'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rules'
]
AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'resil_rules_BAD3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resil_rules_BAD3.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

STATIC_URL = '/static/'

**Comment by fabiocaccamo** [comment]
Did you see the default logo before uploading your one?
I see that your logo name contains some encoded character, try to rename it using alphanumeric chars only, then re-upload it.

**Comment by roderik333** [comment]
@fabiocaccamo No, it's not your job to make people read the django documentation but mentioning that MEDIA_URL and MEDIA_ROOT needs to be set and a means to serve files need to be enabled probably won't hurt productivity ;) Excellent app btw!

@manoantares2 https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-MEDIA_ROOT and https://docs.djangoproject.com/en/2.1/howto/static-files/#serving-uploaded-files-in-development should help.

**Comment by fabiocaccamo** [comment]
@roderik333 you're right, but maintaining open source repositories already requires time that is difficult to obtain and that nobody pays...
