### ISSUE TITLE
missing check for show_inlines_as_tabs in template

### ISSUE THREAD

**Issue by amuzhdaba** [fabiocaccamo/django-admin-interface#390]
There is missing check for the show_inlines_as_tabs condition in the change_form.html (lines 66-73)
So even if I have this feature turned off it populates tabcontent blocks with inlines formsets.
At the same time corresponding condition check for the tablinks is not missing so you'll never see that hidden tabcontent blocks were populated.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/390">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/390/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/390/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@amuzhdaba thank you for reporting this, this feature is hard to maintain because writing tests for it is a bit complicated (#301).

Do you want to submit a PR for fixing this issue?

**Comment by fabiocaccamo** [comment]
@amuzhdaba fixed in `0.28.0` version.
