### ISSUE TITLE
Maintain Active Tab After Clicking "Save and continue editing"

### ISSUE THREAD

**Issue by selected-pixel-jameson** [fabiocaccamo/django-admin-interface#394]
Currently if I have tabs enabled and save a model the active tab will lose it's focus and the first tab will become enabled. It would make sense that if I click "Save and Continue Editing" the active tab would remain active. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/394">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/394/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/394/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@selected-pixel-jameson this is a good idea, thank you.

**Comment by fabiocaccamo** [comment]
@selected-pixel-jameson I just tested this with Firefox, Chrome and Safari without being able to reproduce the issue you reported.
