### ISSUE TITLE
Partial facet support

### ISSUE THREAD

**Issue by nad2000** [fabiocaccamo/django-admin-interface#396]
**Python version** 
3.12, 3.10

**Django version** 
5.0 (5.0.7)

**Package version**
0.28.8

**Current behavior (bug description)**
The admin doesn't show toggle for the counts ("Show counts") with the default "**show_facets**" settings (**ALLOW**). Hence, the user can't turn the counts on:
![image](https://github.com/user-attachments/assets/24d62e5e-2504-4969-8bad-6baa78e73a87)
The counts are shown next to the values provided the "**show_facets**" is set to **ALWAYS**:

![image](https://github.com/user-attachments/assets/e7a415ce-4418-4602-8969-ab8fd500cdb5)

**Expected behavior**
For **Django 5.0** it's expected to have a toggle enabled.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/396">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/396/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/396/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@nad2000 thank you for reporting this!

**Comment by fabiocaccamo** [comment]
fixed in `0.29.0`, any feedback is appreciated.
