### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by ticklemepierce** [fabiocaccamo/django-admin-interface#4]
Hello, my I am trying to change the logo and it is not working.  Is there a configuration I am missing?

Thanks

**Comment by fabiocaccamo** [comment]
Hi, Which Django version are you using?
The file is correctly uploaded?
Could you check with another browser to exclude the possibility of a cache-related issue?

**Comment by vadviktor** [comment]
Hello @fabiocaccamo, I encountered this issue and I am not sure if it's my problem.
I use Django 1.10 (most recent to day) and get the following error when looking at Chrome Dev tools:

```
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/login/admin-interface/logo/avatar.Hyoudou-Issei.jpg
Using the URLconf defined in blog.urls, Django tried these URL patterns, in this order:
^$ [name='index']
^post/
^admin/ ^$ [name='index']
^admin/ ^login/$ [name='login']
^admin/ ^logout/$ [name='logout']
^admin/ ^password_change/$ [name='password_change']
^admin/ ^password_change/done/$ [name='password_change_done']
^admin/ ^jsi18n/$ [name='jsi18n']
^admin/ ^r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$ [name='view_on_site']
^admin/ ^admin_interface/theme/
^admin/ ^auth/group/
^admin/ ^auth/user/
^admin/ ^posts/post/
^admin/ ^(?P<app_label>admin_interface|auth|posts)/$ [name='app_list']
The current URL, admin/login/admin-interface/logo/avatar.Hyoudou-Issei.jpg, didn't match any of these.
```

So I am running the server with `manage.py runserver`, dev mode and am getting the same 404 for the first time when it was trying to access the default svg icon. I uploaded my own but the routing is still messing it up.

My urls.py looks like this:

```python
from django.conf.urls import url, include
from django.contrib import admin

from main.views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='index'),
    url(r'^post/', include('posts.urls')),
    url(r'^admin/', admin.site.urls),
]
```

I am learning Django currently, my knowledge is not complete even with the basics, so just ask me more questions please to be able to help track down this issue.

Thank you very much for all your help you can lend me! 😃

**Comment by fabiocaccamo** [comment]
@vadviktor have you followed step-by-step installation instructions in the README?

**Comment by vadviktor** [comment]
@fabiocaccamo yes I added the apps, did the migrations and collected the static files. The linked urls.py is my main router and it's still a fresh project, there are no other advanced files yet.

Nothing changed by adding your additional settings:

```
Using the URLconf defined in blog.urls, Django tried these URL patterns, in this order:
^media/(?P<path>.*)$
^static\/(?P<path>.*)$
^$ [name='index']
^post/
^admin/ ^$ [name='index']
^admin/ ^login/$ [name='login']
^admin/ ^logout/$ [name='logout']
^admin/ ^password_change/$ [name='password_change']
^admin/ ^password_change/done/$ [name='password_change_done']
^admin/ ^jsi18n/$ [name='jsi18n']
^admin/ ^r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$ [name='view_on_site']
^admin/ ^admin_interface/theme/
^admin/ ^auth/group/
^admin/ ^auth/user/
^admin/ ^posts/post/
^admin/ ^(?P<app_label>admin_interface|auth|posts)/$ [name='app_list']
The current URL, admin/admin-interface/logo/avatar.Hyoudou-Issei.jpg, didn't match any of these.
```

**Comment by vadviktor** [comment]
Do you think it makes a difference that I use Python 3.6? I see you "support" 3.4.

**Comment by fabiocaccamo** [comment]
@vadviktor I don't think that the Python version makes the difference in this case.
I will do some tests as soon as possible.

**Comment by fabiocaccamo** [comment]
@vadviktor I tested with this url conf and I got your same problem:
```python
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
```
then I added static media urls and it worked:
```python
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**Comment by vadviktor** [comment]
Thank you @fabiocaccamo, I can share my source code with you too (it's just a study project) if that would help you help me :)
Well, this issue is not critical or something, though I thought to be good to let you know. :)

**Comment by vadviktor** [comment]
@fabiocaccamo We posted the same time, 🤣 
Thanks, I have a look at it and come back to you ASAP. 👍

**Comment by fabiocaccamo** [comment]
The logo files (original and newly uploaded too) are in an app dir admin-interface/logo because you have not set MEDIA_ROOT and STATIC_ROOT settings in your settings.py. 
https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-MEDIA_ROOT

**Comment by vadviktor** [comment]
@fabiocaccamo Thanks very much for the heads up! I'll let this thread know the results for future reference.

**Comment by vadviktor** [comment]
I have set the `MEDIA_ROOT` and `MEDIA_URL` too as described for Django 1.10, but the logo only appears if I use the additional url setup:

```python
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

I don't know much yet about how Django's url dispatching works, but I may come back to this when I tracked the issue down. 😞

**Comment by fabiocaccamo** [comment]
Yes, that's correct.
The additional url setup is needed for development: https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-files-uploaded-by-a-user-during-development

**Comment by vadviktor** [comment]
@fabiocaccamo I hear you now :) Thank you very much for the help, I think I now understand the situation.
