### ISSUE TITLE
name in Theme model should be primary key, for idempotent deploy.

### ISSUE THREAD

**Issue by belonesox** [fabiocaccamo/django-admin-interface#40]
``name`` in ``Theme`` model should be primary key, for idempotent deploy.

Right now, primary key is autogenerated ``id``,
caused that each
```
     python manage.py loaddata xxxxx.json
```
duplicates some theme.

There should be no different themes with same name.

**Comment by fabiocaccamo** [comment]
Yes, actually if you run twice `python manage.py loaddata admin_interface_theme_bootstrap.json` you will have 2 themes loaded.

Once, pk(s) field was present in `xxxxx.json`, but they have been omitted to avoid pk collisions at `loaddata` time.

The question is:
Why you run loaddata multiple times for the same theme if you don't need it?

**Comment by belonesox** [comment]
Because every deployment should be:
* authomated
* idempotent

Of course, it possible to make it idempotent (lot of ugly code on ansible to check if the theme exists in DB) by why?

**Comment by merwok** [comment]
I think there could be a simpler way:

- keep autogenerated ID
- define name as natural key
- dump fixtures with --natural-key option

**Comment by fabiocaccamo** [comment]
This has been fixed in `0.10.3` version, the solution is a little bit dirty but transparent.
- on `pre_save`, if theme `pk` is not set and another theme with the same `name` exists, just overwrite the existing one.
- `name` field is now **unique**

**Comment by merwok** [comment]
So the behaviour is: if I import a theme, then customize it but don’t change its name, if I import again my data will be overwritten without any confirmation or warning?

**Comment by fabiocaccamo** [comment]
Actually yes, but we could do also the opposite: if I import a theme, then customize it but don’t change its name, **if I import the same theme again it will inherit fields values of the existing one**.

I also added `test_fixtures.py`, you could write a test case which fails for this.

**Comment by merwok** [comment]
I think it’s fine as long as the documentation is clear :)

Now the theme name is its identifier, and we should change the name to keep customizations.  It can be useful to be able to import the original theme again to compare the original with the custom one.

**Comment by fabiocaccamo** [comment]
If you need a custom theme you should create a new theme and not edit an imported one, I will update the README

**Comment by merwok** [comment]
Well I didn’t have the skill to create one from scratch, so starting from an imported them then changing options and images works great!

Now I also need to that I should change the theme name to ensure it’s preserved even if I re-import the original one.  I find the behaviour quite nice after all!
