### ISSUE TITLE
Support for Django 5.1

### ISSUE THREAD

**Issue by anyidea** [fabiocaccamo/django-admin-interface#401]
Hi,
Thank you for the ongoing support and updates to the django-admin-interface package. I noticed that while the package does support Django 5.1, there are some issues with the admin UI that need to be addressed for full compatibility.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/401">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/401/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/401/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@anyidea thank you for reporting this, could you be more specific please? That would be very helpful.

**Comment by anyidea** [comment]
> @anyidea thank you for reporting this, could you be more specific please? That would be very helpful.

The inline style looks abnormal.
![CleanShot 2024-08-26 at 11 22 40@2x](https://github.com/user-attachments/assets/597eaabd-4bf7-4958-b3b2-b6f1166c5338)

**Comment by anyidea** [comment]
With Django 5.0

![CleanShot 2024-08-26 at 11 26 49@2x](https://github.com/user-attachments/assets/ffe52f54-2cb9-4a3f-ac26-ef7b46957c16)

**Comment by juancresc** [comment]
just installed this in the latest django version and got
```

popup_response.js:6 Uncaught TypeError: Cannot read properties of null (reading 'dismissChangeRelatedObjectPopup')Understand this error
popup_response.js:6 Uncaught TypeError: Cannot read properties of null (reading 'dismissChangeRelatedObjectPopup')
    at popup_response.js:6:16Understand this error
```

pop up wont close

**Comment by fabiocaccamo** [comment]
@ahmedsafadii could you please upgrade to `0.28.9` and provide me some feedback about the fieldset style?
