### ISSUE TITLE
Django Style override the Selected Style

### ISSUE THREAD

**Issue by ahmedsafadii** [fabiocaccamo/django-admin-interface#403]
**Python version**
3.12

**Django version**
5.1.1

**Package version**
0.28.8

**Current behavior (bug description)**
the selected style override django style

**Expected behavior**
the django style admin override my selection

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/403">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/403/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/403/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@ahmedsafadii could you please upgrade to `0.28.9` and provide me some feedback?

**Comment by ahmedsafadii** [comment]
Thank you, it works now!
