### ISSUE TITLE
Install django-flat-{theme,responsive} only when needed

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#46]
With recent django versions, it is not necessary to install django-flat-theme and django-flat-responsive.  They could be removed from requirements, and either installed manually by people (with instructions in the docs), or maybe [extras](https://packaging.python.org/guides/installing-using-pip-and-virtualenv/#installing-extras) could be used for a more convenient install method.

**Comment by fabiocaccamo** [comment]
The ideal solution would be to install packages dynamically depending on django version installed, is this possible?

**Comment by merwok** [comment]
No, the environment markers only include thinks like OS and Python version, not other dependencies.  I think the best you can get is an extra: `django-admin-interface[django09]` would depend on django 0.9.* and django-flat-responsive.

**Comment by merwok** [comment]
Sorry I haven’t had time to look into this.
Is it still something interesting, or are you going to support only Django 2+ and this becomes irrelevant?

**Comment by fabiocaccamo** [comment]
Actually support older django versions doesn't require any special effort, so I will not drop them.

I closed this issue only because it's not possible to install packages conditionally depending on django version installed.
