### ISSUE TITLE
Clean up packaging

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#47]
Hello!  I noticed a few places where setup.py is doing a lot more work than required

- PyPI accepts markdown descriptions now: https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
- setuptools lets you put most of the metadata in setup.cfg: https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files
- this method also handles reading the contents of description file automatically
- and getting version number from a module automatically

**Comment by fabiocaccamo** [comment]
Thanks for all suggestions, could you send a PR for all these improvements?

**Comment by merwok** [comment]
Will do!

**Comment by fabiocaccamo** [comment]
@merwok are you working on a PR for this issue?

**Comment by merwok** [comment]
In truth I think that switching to flit could make life easier and would remove `setup.py`!

IMO compiling `.mo` files should be done by every PR that changes translations, or be one of the release tasks (done by a maintainer before releases).  Running lots of commands from `setup.py` is one cause for all the trouble that people have with setuptools.  I prefer small tools that do one thing well!

**Comment by fabiocaccamo** [comment]
I don't know how like would be easier by removing `setup.py` :)
I agree, `.mo` should be compiled by PR.

**Comment by merwok** [comment]
Hello!  Just a ping to say I still want to look into this.

I also have a couple of feature requests to write properly when I have some time + I would be interesting in writing the PRs.

**Comment by fabiocaccamo** [comment]
@merwok Still interested in writing a PR? Otherwise I will close this issue due to inactivity...

**Comment by merwok** [comment]
Yes I’ll send something this month!

**Comment by merwok** [comment]
FYI I have started on this
