### ISSUE TITLE
Cancel button does not work

### ISSUE THREAD

**Issue by nosanity** [fabiocaccamo/django-admin-interface#53]
Although commit https://github.com/fabiocaccamo/django-admin-interface/commit/e3811e26097dbcabd6289dc30fa871f6ccd84aaa fixes cancel button in case of modals, it seems to break that functionality for simple pages (like when you press delete button on object edit page and end up on confirmation page)

**Comment by fabiocaccamo** [comment]
Could you describe me the steps to follow to reproduce the bug?

**Comment by nosanity** [comment]
1. Open edit page for any object which is deletable (i.e. /admin/flatpages/flatpage/1/change/) and press delete button
   OR
   select object(s) on object list page (i.e /admin/flatpages/flatpage/), select delete action and press confirm button to the rigth of actions select box

2. You end up on delete confirmation page. 
Bug: If you press "No, take me back" button bothing happens
Expected: button acts like "back" button in browser

**Comment by fabiocaccamo** [comment]
@nosanity thanks for the report, you can install `0.9.2` version.

**Comment by nosanity** [comment]
thanks for the fast feedback
