### ISSUE TITLE
Relative or absulte path for logo and favicon

### ISSUE THREAD

**Issue by decklord** [fabiocaccamo/django-admin-interface#54]
Hi, 

We noticed that the logo and favicon have to be hosted by the app itself. 

Sadly we are running our django-admin site in a cluster, so if I upload the logo, it will be loaded on a certain machine, not the others, making the upload feature a bit useless. It auto scales, so machines are deleted and created.

We could include this pre-loaded in the cluster image, but it would be nice to have an option to just put an url in this field and read it from the web.

**Comment by merwok** [comment]
But isn’t that a generic django issue, not specific to django-admin-interface?

If I have a dynamic cluster or instances on heroku, then I have to use django-storages to configure a persistent media file storage, independent of each instance’s filesystem.

**Comment by fabiocaccamo** [comment]
@decklord an alternative url field could be easily added, but as suggested by @merwok you should use `django-storages` to configure a persistent media file storage.

How do you handle all other file uploads?
