### ISSUE TITLE
Related modal does not close

### ISSUE THREAD

**Issue by deepam1803** [fabiocaccamo/django-admin-interface#55]
Whenever the save button on related modal is clicked, the new record is saved but the modal doesn't close. 
<img width="1155" alt="screenshot 2019-03-07 at 11 43 26 am" src="https://user-images.githubusercontent.com/19245659/53935961-45343200-40ce-11e9-9e06-046da871a5a0.png">
Keeps on showing this

**Comment by fabiocaccamo** [comment]
@deepam1803 could you tell me the version of:
- `python`
- `django`
- `django-admin-interface`

Could you check also in the browser console if there is any JavaScript error or useful log?

**Comment by deepam1803** [comment]
django version 2.1.1
python version 3.5.4
django-admin-interface 0.9.3

**Comment by fabiocaccamo** [comment]
@deepam1803 is there any log in the console?

**Comment by deepam1803** [comment]
Yes, I can close the modal after clicking outside. Also, there are no error logs. The post request that it does to update the values return code 200 response. The changes I have done in modal are also applied in the database.

**Comment by fabiocaccamo** [comment]
@deepam1803 I just manually tested the following test cases:

- add related object in changelist
- change related object in changelist
- delete related object in changelist
- add related object in detail page
- change related object in detail page
- delete related object in detail page

I can't reproduce the error, does your test case match one case listed above or I could test something else?

**Comment by deepam1803** [comment]
I am using djangi auto complete along with these. i am adding a  related object in changelist. i guess the problem is withnusing django auto complete field.

**Comment by fabiocaccamo** [comment]
Could you try to remove django auto complete and check if the problem persists?

If we are 100% sure that the problem is caused by django auto complete I will do some tests to improve compatibility.

**Comment by carlosmonari** [comment]
Hi my dearest friend,

when we use raw-id-field whith django-admin-interface, exist a error in the new window invoked to select a register. the new window is not closed after select a register.

this error occurr in all browser's (IE, Chrome, Firefox ...)

i use to develop:
django 2.1
python 3.7

**Comment by fabiocaccamo** [comment]
@deepam1803 are you using [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light)?

**Comment by merwok** [comment]
FTR I am using https://github.com/farhan0581/django-admin-autocomplete-filter (works with modern django autocomplete_fields) and there are no problem with django-admin-interface.

**Comment by deepam1803** [comment]
@fabiocaccamo  yes i am using django-autocomplete-light

**Comment by fabiocaccamo** [comment]
@deepam1803 could you try to remove django auto complete and check if the problem persists?

**Comment by fabiocaccamo** [comment]
@deepam1803 I just tested `django-autocomplete-light` with python 2.7 and 3.6 and everything works fine.
Could you install `0.10.1`, run `python manage.py collectstatic --clear --noinput` and check again?

**Comment by fabiocaccamo** [comment]
@deepam1803 I did some tests with `django-autocomplete-light` on python 2 and python3, everything worked fine. Is it possible to check your project somewhere online?

**Comment by deepam1803** [comment]
@fabiocaccamo  I installed 0.10.1 and everything works fine now. Thanks
