### ISSUE TITLE
raw-id-field whith django-admin-interface

### ISSUE THREAD

**Issue by carlosmonari** [fabiocaccamo/django-admin-interface#58]
Hi my dearest friend,

when we use raw-id-field whith django-admin-interface, exist a error in the new window invoked to select a register. the new window is not closed after select a register.

this error occurr in all browser's (IE, Chrome, Firefox ...)

i use to develop:
django 2.1
python 3.7

**Comment by fabiocaccamo** [comment]
@carlosmonari thanks for reporting the issue, it has been fixed in `0.10.2` version.

**Comment by carlosmonari** [comment]
Thank you so much!
This package is great to make skins for apps!
It's pleasure to help find bugs

Arrivederci.

**Comment by fabiocaccamo** [comment]
Thank you @carlosmonari,
I'm really glad that many people appreciate this package.

If you have any idea about new features or integration with 3rd party packages just open a new issue.
