### ISSUE TITLE
Better releases

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#59]
- make sure to update translations before releases
- write a changelog
- write upgrade notes in the github release page

**Comment by newpanjing** [comment]
I recommend a better theme: simpleui
[https://github.com/newpanjing/simpleui/](https://github.com/newpanjing/simpleui/)
or pip install:
```python
pip install django-simpleui
```

**Comment by newpanjing** [comment]
Why delete my comment?~ haha~😝

**Comment by newpanjing** [comment]
Your theme is also good, great!
