### ISSUE TITLE
Logo not showing though MEDIA_ROOT and MEDIA_URL are set

### ISSUE THREAD

**Issue by coveritytest** [fabiocaccamo/django-admin-interface#60]
Unfortunately it does not run out of the box. I added

MEDIA_ROOT = os.path.join(BASE_DIR, 'admin_interface/public/media/')
MEDIA_URL = '/media/'

to settings.py, but the logo will be uploaded to

http://127.0.0.1:8000/media/admin-interface/logo/mylogo.svg

which leads to

[26/Mar/2019 21:55:52] "GET /media/admin-interface/logo/mylogo.svg HTTP/1.1" 404 2081

Do I have to adjust another setting? I'm using django 2.1 and the latest version of django-admin-interface which I installed with pip3 install django-admin-interface.

**Comment by merwok** [comment]
I don’t know if django will create the subdirectories `admin_interface/public/media`.

Why not have a more usual setting such as `MEDIA_ROOT = os.path.join(BASE_DIr, "media")` ?

**Comment by coveritytest** [comment]
I did what you proposed, but it still doesn't find the logo. The GET request is still the same:

[27/Mar/2019 07:36:29] "GET /media/admin-interface/logo/mylogo.svg HTTP/1.1" 404 2081

The logo now is saved at media in the base dir, but I have the feeling that the URL resolution is failing here. Do I have to adjust the url.py respectively the urlpatterns?

**Comment by fabiocaccamo** [comment]
@coveritytest this is a problem related to your [settings](https://docs.djangoproject.com/en/2.1/ref/settings/) and not to this package, btw these are my settings values:

```python
MEDIA_ROOT = os.path.join(BASE_DIR, 'public/media/')
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'public/static/')
STATIC_URL = '/static/'
```

**Comment by coveritytest** [comment]
I'm using a fresh Django installation in a virtualenv without changing any settings or urls and it's not working, so it's a problem of the repo, because standard users are using the standard configuration and with this your repo doesn't work. Even with the settings you just provided it doesn't work.

**Comment by fabiocaccamo** [comment]
@coveritytest this package uses media and static files as described in the `django` documentation. 

This issue should be common to all users, so probably it is related to your setup.

Can you upload all other media files?
Have you tried to upload a `.jpg` or `.png`?

**Comment by merwok** [comment]
I can confirm I don’t have these issues, not with default FileStorage locally and not with Boto3S3Storage on servers.

**Comment by coveritytest** [comment]
Same problem with .jpg. Steps to reproduce:

mkvirtualenv admin-interface
pip3 install django
pip3 install django-admin-interface
django-admin startproject customized
cd customized/
code customized/settings.py (adjust INSTALLED_APPS, MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL)
python manage.py migrate
python manage.py collectstatic
python manage.py createsuperuser
python manage.py runserver

**Comment by merwok** [comment]
Sorry, the collectstatic discussion was wrong, this is a bout media files.

On my server, the logo is served at `https://{id}.cloudfront.net/admin-interface/logo/logo_abcd.png`

The template tag does not use `static` but `{{ theme.logo.url }}`.

Are your other static files and media files ok?  It really seems that there is a problem in your settings, not in this lib.

Why does your MEDIA_ROOT use `BASE_DIR + 'admin_interface/public/media/'` ?
Django media settings should make sense for your site (base dir + media or uploads or anything else), it is not coupled to the installed apps.
