### ISSUE TITLE
django-dynamic-raw-id whith django-admin-interface

### ISSUE THREAD

**Issue by carlosmonari** [fabiocaccamo/django-admin-interface#61]
Hi again Fabio,

when we use a external package django-dynamic-raw-id (https://github.com/lincolnloop/django-dynamic-raw-id) whith django-admin-interface, 

exist a error in the new window invoked to select a register. 

the new window is not closed after select a register.

this bug occur like as described in March 21 (raw-id-field whith django-admin-interface issue #58)

this error occurr in all browser's (IE, Chrome, Firefox ...)

i use to develop:
django 2.1
python 3.7

Thanks again.

**Comment by fabiocaccamo** [comment]
@carlosmonari thank you for reporting this issue.
I will fix the compatibility as soon as possible.

**Comment by fabiocaccamo** [comment]
Fixed in `0.10.4`

**Comment by carlosmonari** [comment]
Mr Fabio,

Again, good job.

i tested in my application and works correctly

thanks for this

**Comment by carlosmonari** [comment]
Hi Mr. Fabio

In this version 0.10.5 the problem return.

Its possible correct this issue again ?

**Comment by fabiocaccamo** [comment]
@carlosmonari nothing has changed from `0.10.4` to `0.10.5` that could have broken this functionality.
Could you please check:
-  `python` version
-  `django` version
-  `django-dynamic-raw-id` version
