### ISSUE TITLE
Don't hard-code media type for favicon 

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#64]
Hello!  The template hard-codes `type="image/x-icon"` for the link rel=icon.
Specs and browsers don’t require to use the Microsoft ICO file format; PNG is a very common choice I think.

If the attribute must be present (I forgot), it should be accurate depending on the image used.

**Comment by fabiocaccamo** [comment]
Could you send a PR?

**Comment by merwok** [comment]
It seems that `type` is not required for `link` element in HTML5.

I’ll do some tests and send a PR when I can!

(if there are browser compat issues, I’ll use the stdlib mimetypes module, I don’t think it’s great but it should be good enough.)

**Comment by merwok** [comment]
Thanks for merging the PR!  I didn’t do browser testing but it's in the spec after all, so we should be good.  Also easy to change (do the mimetype idea) if people report problems!
