### ISSUE TITLE
Reverse for 'set_language' not found

### ISSUE THREAD

**Issue by jforlenza-bnydc** [fabiocaccamo/django-admin-interface#67]
I just installed this package on a new project im working on, howerver im getting the following error:

`NoReverseMatch at /admin/`
`Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.`

[Full Debug Info](http://dpaste.com/1RCFNCE)

**Comment by fabiocaccamo** [comment]
You have not added i18n urls to urls.
Is your project multi-language?

**Comment by fabiocaccamo** [comment]
@jforlenza-bnydc you can install `0.11.1`.

**Comment by jforlenza-bnydc** [comment]
Thank you, that fixed the issue, I was using a boilerplate for experimenting and noticed it had some international options enabled

**Comment by fabiocaccamo** [comment]
@jforlenza-bnydc the language-chooser to work correctly needs:

- `settings.USE_I18N = True`
- 2 or more languages listed in `settings.LANGUAGES`
- i18n urls and i18n admin urls: 
```python
from django.conf.urls.i18n import i18n_patterns

urlpatterns += [url(r'^i18n/', include('django.conf.urls.i18n')),]`
urlpatterns += i18n_patterns(url(r'^admin/', admin.site.urls))
```

**Comment by Sushang-Agnihotri** [comment]
project's urls.py :
urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

project's settings.py : 
JAZZMIN_SETTINGS = {
    "language_chooser": True,
}

**Comment by Sushang-Agnihotri** [comment]
> project's urls.py :

```
urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]
urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

```
> project's settings.py : 

```
JAZZMIN_SETTINGS = {
    "language_chooser": True,
}

```

**Comment by fabiocaccamo** [comment]
@Sushang-Agnihotri this is not JAZZMIN.

**Comment by shourya2006** [comment]
> path("i18n/", include("django.conf.urls.i18n")),

Its showing i18n not defined

**Comment by merwok** [comment]
Please paste the exact, full error message.

**Comment by fabiocaccamo** [comment]
@shourya2006 probably you're doing something wrong, it is still there: 
https://github.com/django/django/blob/main/django/conf/urls/i18n.py

Anyway this is not an issue of this package.

**Comment by djangomarmaris** [comment]
add this path("i18n/", include("django.conf.urls.i18n")),   central urls.py

**Comment by maamounhajnajeeb** [comment]
`settings.USE_I18N = True`

That's exactly what I've missed

thank you very much man

**Comment by fabiocaccamo** [comment]
@maamounhajnajeeb thanks for the update, it might be useful to someone else.

**Comment by omarraafat14** [comment]
> > project's urls.py :
> 
> ```
> urlpatterns = [
>     path("i18n/", include("django.conf.urls.i18n")),
> ]
> urlpatterns += i18n_patterns(path("admin/", admin.site.urls))
> ```
> 
> > project's settings.py :
> 
> ```
> JAZZMIN_SETTINGS = {
>     "language_chooser": True,
> }
> ```

adding django.conf.urls.i18n worked for me

**Comment by eraliabd** [comment]
logout page

![image](https://github.com/fabiocaccamo/django-admin-interface/assets/91982815/efaf9129-2f3b-4f76-994a-f10a4826c31c)
When logging out, it says that the page is not working, why?

**Comment by fabiocaccamo** [comment]
@eraliabd this package doesn't change urls at all, so the problem is somewhere else in your project.
