### ISSUE TITLE
Interested in a sidebar?

### ISSUE THREAD

**Issue by lorenzomorandini** [fabiocaccamo/django-admin-interface#70]
Hi, as title, would you be interested in a PR implementing a simple sidebar (sidemenu) for the admin? The idea would be to:

- Auto generate menù items for applications/models registered in admin (with the possibility to exclude them), based on user permissions
- Add custom menù items with custom urls

**Comment by fabiocaccamo** [comment]
@lorenzomorandini it sounds great, if it is a generic solution that could be useful to many people the answer is absolutely yes.
Could you explain me better the use case?
Have you any screenshot or even better an online demo?

**Comment by lorenzomorandini** [comment]
We already implemented it once but I re-looked into it to see if it can be done in a better way. Unfortunately, there doesn't seem to be a way of doing it without completely copying the "base.html" file, which I doubt you are fine with.

**Comment by fabiocaccamo** [comment]
I think that replace the whole `base.html` for a new and optional feature is not the best choice.
Have you used it just once or in multiple projects? I would like to add only generic features that solves common problems.

**Comment by lorenzomorandini** [comment]
More than once, it's just a configurable sidebar to display apps/models or custom links. Unfortunately it doesn't seem possible without overriding base.html completely. Feel free to close the issue

**Comment by fabiocaccamo** [comment]
Ok, thank you for the feedback.
