### ISSUE TITLE
Python 2/3 issue when upgraded to Django 3.0

### ISSUE THREAD

**Issue by pablondrina** [fabiocaccamo/django-admin-interface#71]
**Python version**
3.6.9

**Django version**
3.0

**Current behavior (bug description)**
<Sorry, 'novice coder' alert!>
I'm updating my project to Django 3.0, and then I've got this 2 errors when I've prompted the runserver command:
**1)**
  File "/home/pablo/.local/share/virtualenvs/backend-7xANml56/lib/python3.6/site-packages/admin_interface/models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible, force_text
ImportError: cannot import name 'python_2_unicode_compatible'

**2)**
  File "/home/pablo/.local/share/virtualenvs/backend-7xANml56/lib/python3.6/site-packages/admin_interface/models.py", line 15, in <module>
    @python_2_unicode_compatible
NameError: name 'python_2_unicode_compatible' is not defined

I only could run the project normally by commenting those two lines (7 and 15 of the admin_interface.models.py file). Guessing if there is a better solution?

**Expected behavior**
?

**Comment by fabiocaccamo** [comment]
Update package to the latest version.

**Comment by pablondrina** [comment]
Thanks for your reply. But unfortunately I've tried this and got the same
errors.

Em sáb., 7 de dez. de 2019 às 19:20, Fabio Caccamo <notifications@github.com>
escreveu:

**Comment by fabiocaccamo** [comment]
Which package version have you installed?

**Comment by fabiocaccamo** [comment]
@pablondrina any update?

**Comment by pablondrina** [comment]
Version 0.12.0


Em seg., 9 de dez. de 2019 às 06:22, Fabio Caccamo <notifications@github.com>
escreveu:

**Comment by fabiocaccamo** [comment]
It's impossible that you are using `0.12.0` version and see this error.

Download `0.12.0` version from [pypi](https://pypi.org/project/django-admin-interface/0.12.0/), open `models.py` and you will note that there is not the import that raises the exception you reported.
```python
from django.utils.encoding import python_2_unicode_compatible, force_text
```
This issue is invalid, if you still have any problem please open another issue.
