### ISSUE TITLE
Popup for related models creation fires a javascript error when "Related modal" is inactive

### ISSUE THREAD

**Issue by morlandi** [fabiocaccamo/django-admin-interface#76]
**Python version**
Python 3.7.6

**Django version**
Django 3.0.4

**Package version**
django-admin-interface==0.12

**Current behavior (bug description)**
The Popup for related models creation doesn't work when "Related modal" is inactive, due to this javascript error:

     Uncaught TypeError: Cannot read property 'replace' of undefined
        at windowname_to_id (:8000/static/admin/js/admin/RelatedObjectLookups.js:19)
        at dismissAddRelatedObjectPopup (:8000/static/admin/js/admin/RelatedObjectLookups.js:77)
        at popup_response.js:43
        at popup_response.js:52

**Expected behavior**
Since the standard Django admin is working correctly, this problem seems related to the presence of django-admin-interface.

I did a very basic setup of a simple Django project to reproduce the error in a simplified enrvironment.

The project and some screenshots to better explain the problem are available here:

https://github.com/morlandi/test-admin-interface

**Comment by fabiocaccamo** [comment]
@morlandi thank you for reporting this, I will debug and fix it as soon as possible.

**Comment by morlandi** [comment]
Great ! I'm thinking about the possibility to provide a specific unit test, in order to further investigate this problem with previous versions of Django and/or  django-admin-interface.
Not sure if I can cope the the popup window, though ;)
Thank you for this great app !

**Comment by fabiocaccamo** [comment]
@morlandi I quickly tested it, and it seems to be a **Django issue**. To verify this just disable admin interface package by set `USE_ADMIN_INTERFACE=False` in `settings` and you will see that the problem persists.

**Comment by morlandi** [comment]
@fabiocaccamo  I already checked it ... with USE_ADMIN_INTERFACE=False it just works.
Let me check again an I'll send some screenshots on this.

Did you clear the browser cache after changing the setting ?

**Comment by morlandi** [comment]
I can confirm that with the standard Django admin it is working:

<img width="1065" alt="Screenshot 2020-03-09 at 10 05 27" src="https://user-images.githubusercontent.com/299854/76198191-e9731c00-61ed-11ea-8cc6-09123102d137.png">

<img width="1025" alt="Screenshot 2020-03-09 at 10 05 39" src="https://user-images.githubusercontent.com/299854/76198198-ed9f3980-61ed-11ea-9f0d-3601eaeb0dae.png">

**Comment by fabiocaccamo** [comment]
It opens the related popup, but when I save it, the popup doesn't dismiss correctly.

**Comment by morlandi** [comment]
> As you can see here the related modal css/js are included only if related modal is active.

mhhh .. interesting .. this is really puzzling.

I started again from scratch, and must confirm that the problem doesn't show up with Django admin alone.
I made a screencast of what I did .. please have a look:

https://vimeo.com/396461322

**Comment by morlandi** [comment]
The javascript includes .. django alone on the left, django + admin-interface on the right.
They look much the same .. must be some JS quirk ;)

![Screen Shot 2020-03-09 at 15 59 33](https://user-images.githubusercontent.com/299854/76227272-56eb7080-621f-11ea-9e6c-bfbf55dc7cce.png)

**Comment by fabiocaccamo** [comment]
Thank you for the screencast, I found it very useful. I will investigate this issue.

**Comment by fabiocaccamo** [comment]
@morlandi could you check if the `related-modal.js` script is included when the modal is disabled?

**Comment by morlandi** [comment]
No, `related-modal.js` is not included.
However, I noticed it's not included with `USE_ADMIN_INTERFACE = False` (that is: with the "ordinary" Django admin interface) either.

**Comment by fabiocaccamo** [comment]
@morlandi I pushed the fix on master, could you test it with and without modal active?
If it is everything ok I release a new version on `pypi`.

**Comment by fabiocaccamo** [comment]
This bug always existed, but nobody discovered it because nobody disable the related modal, why you did it? :D

**Comment by morlandi** [comment]
> @morlandi I pushed the fix on master, could you test it with/without related-modal active?
> If it's everything ok also for you, I release a new version on `pypi`.

Thank you @fabiocaccamo ... I will test it soon with both Django 2 and Django 3, and will give you a feedback on this

**Comment by fabiocaccamo** [comment]
@morlandi I wait your feedback to release a new version, thank you.

**Comment by morlandi** [comment]
> This bug always existed, but nobody discovered it before because nobody disable the related modal, why you did it? 😂

Since you're asking ... I consider the related modal a TREMENDOUS IMPROVEMENT for UX, and honestly don't see any reason for disabling it.
I was just playing around with the flags provided by `django-admin-interface` to familiarise with it. Really great stuff, thank you for sharing.

In the past, I had the chance to use several admin interfaces: mostly django-grappelly, and occasionally django-suit and django-boostrap-admin.
Surely interesting solutions, but also a source of headaches when you migrate to a new release of Django, so I ended up using the native admin, instead.

django-admin-interfaces seems so much lighter, and I'm reconsidering this ...
Related modal being the very first motivation ;)

**Comment by fabiocaccamo** [comment]
@morlandi thank you very much, I am very pleased by your feedback.

I love the default django admin, it works perfectly, but it lacks of personality and customization, clients don't like it... and neither me!
So I looked for alternatives, but for one reason or another I was always unsatisfied.
I realized that I didn't want something different, I didn't need a rewrite of the admin, but just something better and easy to maintain over the time.
I started by overriding the `base_site.html` template for each project to customize logo and override colors, then after few projects the abstraction was pretty clear, and I moved it to an external package.

If you have any idea of some new features that could be useful to everyone just open a new issue.

**Comment by morlandi** [comment]
> If you have any idea of some new features that could be useful to everyone just open a new issue.

I surely will ;)

**Comment by morlandi** [comment]
@fabiocaccamo I did some tests in different contexts; these are the results:

| Django-admin-interface | Django 2.2.12 |  | Django 3.0.5 |  |
|------------------------------------|----------------------|------------------------|----------------------|------------------------|
|  | Related Modal Active | Related Modal Inactive | Related Modal Active | Related Modal Inactive |
| V0.12.1 | OK | FAIL | OK | FAIL |
| 6aec3c0 (fix 2020-04-07 on master) | OK | OK | OK | OK |

Problem solved ! 
Thank you.

You might want to close this issue ;)

**Comment by fabiocaccamo** [comment]
@morlandi thank you for having tested it well. You can upgrade to `0.12.2` version.
