### ISSUE TITLE
Related modal doesn't work

### ISSUE THREAD

**Issue by jacoposartini** [fabiocaccamo/django-admin-interface#80]
**Python version**
3.8.1

**Django version**
Version: 3.0.5
I also tried version: 2.2

**Package version**
Version: 0.12.2

**Current behavior (bug description)**
I use django-storages and Amazon s3 as backend storage for media and static files.

Everything works perfectly, except the related modal which is not shown, and instead there is always the default popup.

I did several tests and was amazed to see that the related modal works by disabling django-storages. 

when I run collectstatic with s3 backend I get the following warnings:
```
Found another file with the destination path 'admin/js/cancel.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/popup_response.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
```
Theoretically since in installed apps, there is first admin_interface, those two files should not be overwritten by django.contrib.admin.

My installed apps:
```
INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "storages",
    .....
]
```

**Expected behavior**
Related modal instead of the old popup window.

I hope you can help me, thank you in advance!

**Comment by fabiocaccamo** [comment]
Thank you for reporting this problem.

The related modal to work properly needs to override 2 js files of the django admin, it is for this reason that `admin_interface` should be listed before in `settings.INSTALLED_APPS`. It seems that `django-storages` ignores this order.

Could you try to investigate a little bit more? Maybe this is more a `django-storages` issue.

**Comment by jacoposartini** [comment]
I forced the js files in question of admin_interface in the  admin static files folder.

The content of /static/admin/js/popup_response.js is the same of
https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/static/admin/js/popup_response.js

but the related modal still not working :(

I'll do some more tests in the morning...

this kind of thing has never happened before?

**Comment by fabiocaccamo** [comment]
In the admin, the active theme has the related modal checkbox checked?

Is there any error log in the browser console?

**Comment by jacoposartini** [comment]
Looking in the console I noticed this warning "Loading failed for the <script> with source ...". 

Opening directly the src link I reconstituted the error "SignatureDoesNotMatch" so it's a problem of how this file was handled by django-storages.

But I still can't explain why this happened only with these files...

Thank you for answering me so quickly and for making a django module that I really like :)

**Comment by jacoposartini** [comment]
If something similar happened to someone, I solved it by setting in my custom storage class
`querystring_auth = False`

**Comment by fabiocaccamo** [comment]
Thank you for the quick feedback, this is a really strange bug, I suggest you to open an issue on `django-storages`, maybe it could be useful to other people in future.

I’m really glad you like this package, after long time people seems having noticed it.
