### ISSUE TITLE
Unable to set empty title in Theme settings

### ISSUE THREAD

**Issue by MalikBagwala** [fabiocaccamo/django-admin-interface#82]
Setting title as empty String 

![image](https://user-images.githubusercontent.com/23068029/82176581-cf903c80-98f4-11ea-81ce-c1423a4df3d7.png)

Results in the default title

![image](https://user-images.githubusercontent.com/23068029/82176616-e3d43980-98f4-11ea-8fa3-1fb2cd7115c4.png)

While I want to achieve this

![image](https://user-images.githubusercontent.com/23068029/82176651-00707180-98f5-11ea-91d8-9d9bbb38fb55.png)

## Package Version  - django-admin-interface@0.12.2 

A better Design pattern would be to prefil the title in as Django Admin and then user can change it to whatever he/she likes (could be a trend across the theme form)

**Comment by fabiocaccamo** [comment]
This is the correct behavior, if you want hide the title just uncheck the `visible` checkbox.
