### ISSUE TITLE
Unreadable text in autocomplete multi-selects

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#83]
**Python version**
3.8

**Django version**
3.0.6

**Package version**
0.12.2

**Current behavior (bug description)**
In a multi-select field using autocomplete (django admin feature), selected options are not readable.  Django’s autocomplete.css sets a white font color, django-admin-interface inline CSS defines white background color.

**Expected behavior**
Text should be readable :slightly_smiling_face:   I am not sure if the background or text color should change, though; should probably match the behaviour of custom selects.

A quick workaround:
```css
.select2-container--admin-autocomplete .select2-results__option--highlighted[aria-selected] {
  color: inherit;
```

**Comment by fabiocaccamo** [comment]
@merwok thank you for reporting this, it will be fixed within the next release.

**Comment by merwok** [comment]
Any date for that? :slightly_smiling_face:

**Comment by merwok** [comment]
I notice now that the background color is not hard-coded to white, but uses theme → banner → background color, which seems strange.

**Comment by fabiocaccamo** [comment]
@merwok could you send a PR?

**Comment by fabiocaccamo** [comment]
@merwok I just tested it with:
-  `Python 3.8.0` 
-  `Django 3.0.5` and `Django 3.0.7`
-   Both default theme and custom theme

but I can't replicate the problem...

**Comment by merwok** [comment]
Could you add a screenshot?

**Comment by merwok** [comment]
Example with option `super` highlighted and invisible:
![multi-select](https://user-images.githubusercontent.com/635179/84511086-04917400-ac94-11ea-9b28-ebd91a66385a.png)

CSS:
![css](https://user-images.githubusercontent.com/635179/84511085-04917400-ac94-11ea-9309-1ad3340f9757.png)

**Comment by fabiocaccamo** [comment]
@merwok I can't add it now, but I will do. In any case I tested it with both `ForeignKey` and `ManyToMany` fields without having this issue.

This is my test matrix I used:
browsers: chrome, safari, firefox (latest versions)
python: 3.8
django: 3.0.5, 3.0.7

What browser are you using?
Could you ask to someone else to test it?

**Comment by fabiocaccamo** [comment]
@cmc333333 @cereigido @browniebroke could you please verify if you have this issue or not?

**Comment by merwok** [comment]
I use Firefox, let me test with Chromium.

**Comment by merwok** [comment]
Same result on Chromium.  But I realize that testing browsers does not make sense, as the problem comes from the CSS files!

Django CSS has a white text for the selected/highlighted option.
DAA adds a white background color (taken from `theme → banner → background color`): this could be removed?

**Comment by fabiocaccamo** [comment]
@carlosmonari could you check please if also you have this issue?

**Comment by carlosmonari** [comment]
i didn't reproduce this issue in my test 

See my screen 
![screen_test](https://user-images.githubusercontent.com/3496698/86409955-48263f00-bc90-11ea-9ddc-b104e84463e6.png)

**Comment by fabiocaccamo** [comment]
@merwok I understood the problem. The dynamic background color used by the theme is `background-color: {{ theme.css_header_background_color }};`, so I imagine you set a white color for your header.

**Comment by merwok** [comment]
Just realized the same issue was also here with autocomplete list filters (https://github.com/farhan0581/django-admin-autocomplete-filter/).  The update fixes both, thanks! :shipit:

**Comment by fabiocaccamo** [comment]
Perfect!
