### ISSUE TITLE
admin css is not showing

### ISSUE THREAD

**Issue by Hamza-Lachi** [fabiocaccamo/django-admin-interface#84]
**Python version**
Python 3.7.7

**Django version**
3.0.6

in the admin, I think the CSS is not working when I deploy my whole site static is working but the admin static is not working

how can I fix this?

screenshots

![Screenshot from 2020-05-27 11-07-50](https://user-images.githubusercontent.com/53256322/83037945-6605e180-a00a-11ea-9015-1b747aa405ca.png)

my debug is false

**Comment by fabiocaccamo** [comment]
@Hamza-Lachi have you run `python manage.py collectstatic`?

**Comment by fabiocaccamo** [comment]
@Hamza-Lachi the admin css is dynamic to allow customizations, so if you are deploying a static project it doesn't work.

**Comment by Hamza-Lachi** [comment]
yes, i do

**Comment by Hamza-Lachi** [comment]
You have requested to collect static files at the destination
location as specified in your settings:

    /home/django/emailv4/staticfiles

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Found another file with the destination path 'admin/js/popup_response.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/cancel.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

0 static files copied to '/home/django/emailv4/staticfiles', 487 unmodified.

**Comment by Hamza-Lachi** [comment]
> @Hamza-Lachi the admin css is dynamic to allow customizations, so if you are deploying a static project it doesn't work.

Sorry, I can't understand

can you please be clear

**Comment by fabiocaccamo** [comment]
This package generates the css dynamically directly in the admin html, you can check it by looking the page source with the browser.

**Comment by Hamza-Lachi** [comment]
@fabiocaccamo I changed the static root folder to static before I set that to static files now it's working

Thanks!

You Guys Are Awesome!

**Comment by fabiocaccamo** [comment]
@Hamza-Lachi thank you very much!!

**Comment by vibhanshu2001** [comment]
@Hamza-Lachi can you be more specific how your error got resolved? Can you share your code snippets?

**Comment by myst-darkfire** [comment]
I'm facing same problem can you please help me out!!!!

**Comment by merwok** [comment]
It is not possible to debug a problem with zero information about it!
