### ISSUE TITLE
Change Password form not visible in the admin interface (BaseUser)

### ISSUE THREAD

**Issue by MalikBagwala** [fabiocaccamo/django-admin-interface#88]
This is how the default django password field (BaseUser) look like
![image](https://user-images.githubusercontent.com/23068029/86213584-8c81e400-bb97-11ea-9b30-c773a02f462f.png)

While this is how the admin interface customizes it

![image](https://user-images.githubusercontent.com/23068029/86213773-d5399d00-bb97-11ea-9369-16c6ac543fe1.png)

as you can see there is no provision to change password, also the route itself does not exist
![image](https://user-images.githubusercontent.com/23068029/86213909-0e720d00-bb98-11ea-88e7-c81459570fcb.png)

**Comment by fabiocaccamo** [comment]
I think that this issue is not related to this library, this library never changes the dom, so there could be only a wrong color, nothing more. Try to disable `django-admin-interface` and check if the problem persists.

**Comment by MalikBagwala** [comment]
@fabiocaccamo 

you are right. It seems I was extending the wrong model
**Before:**
```
from biosys.crop import models

class SystemUserAdmin(models.SystemUser):
    list_display =  ("uuid",)
    pass
```

**After:** 
```
from django.contrib.auth.admin import UserAdmin

class SystemUserAdmin(UserAdmin):
    list_display = UserAdmin.list_display + ("uuid",)
    fieldsets = UserAdmin.fieldsets + (("Extra Fields", {"fields": ("number",),},),)
    pass
```
