### ISSUE TITLE
How to extend the `django-admin-interface` (insert custom elements, custom styling)

### ISSUE THREAD

**Issue by MalikBagwala** [fabiocaccamo/django-admin-interface#89]
Hello, 

I would like to know how to extend the django admin interface look and feel (by adding custom HTML and CSS)

for eg.

## I want to insert and style simple text inside the `h1` header

![image](https://user-images.githubusercontent.com/23068029/86877652-eab54680-c104-11ea-971d-1bd9e2ff1144.png)

## Also for better context this is how my directory structure looks like

![image](https://user-images.githubusercontent.com/23068029/86877751-1801f480-c105-11ea-9bb5-14f548f53cad.png)

**Comment by fabiocaccamo** [comment]
@MalikBagwala the purpose of this library is to simplify some common customizations, if you create a new theme you can change the admin title and/or logo. If you need to do something different you must [override the admin templates](https://docs.djangoproject.com/el/3.0/howto/overriding-templates/).

**Comment by MalikBagwala** [comment]
@fabiocaccamo  Could you please ellaborate the process? even after countless tries I am  not able to do that. A detailed explaination will be highly appreciated.

**Comment by merwok** [comment]
That’s really a Django question.  If the linked guide doesn’t help, maybe you could describe your problem in detail (with file layouts, what you want to see, what you see (output or error messages)) on StackOverlow and give me the link so that I can try to help you.
