### ISSUE TITLE
Calendar bug

### ISSUE THREAD

**Issue by mapeveri** [fabiocaccamo/django-admin-interface#9]
Hi, when i click in day on the calendar, the console javascript display this message.

![image](https://cloud.githubusercontent.com/assets/6276555/22111093/d6ed0c72-de3c-11e6-9ac6-ddcfe8e2f2aa.png)

This is an error of theme or of django?

Thanks!

**Comment by fabiocaccamo** [comment]
I think it's a Django error, could you retry after having removed admin-interface from installed apps?
Thanks

**Comment by mapeveri** [comment]
Yes, it's a Django error. Thanks!
