### ISSUE TITLE
Logo used in django admin is not working in production

### ISSUE THREAD

**Issue by nabinkhadka** [fabiocaccamo/django-admin-interface#90]
**Python version**
3.8

**Django version**
2.2.14

**Package version**
0.12.2

**Current behavior (bug description)**
Logo uploaded from django admin interface is not serving properly in production served by nginx. I am confused as why each page's logo has different URL. For example see few of the URLs it is requesting below:

Login page logo:
```
nginx_1  | 172.19.0.1 - - [11/Jul/2020:13:28:43 +0000] "GET /login/staticfiles/logo.png HTTP/1.1" 404 77 "http://127.0.0.1:1337/login/?next=/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "-"
```

```
nginx_1  | 172.19.0.1 - - [11/Jul/2020:15:09:41 +0000] "GET /app_name/somemodel/staticfiles/logo.png/change/ HTTP/1.1" 302 0 "http://127.0.0.1:1337/app_name/some_model/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "-"

```

**Expected behavior**
Logo should be served correctly.

**Comment by nabinkhadka** [comment]
I don't know why this is necessary, but I had to override the templates/admin/base_site.html as shown in screenshot.
![Screen Shot 2020-07-11 at 22 31 11](https://user-images.githubusercontent.com/6050613/87229284-993bde80-c3c6-11ea-91f7-583a0a53cb55.png)

**Comment by merwok** [comment]
Have you configured media files properly?  If you have nginx, you want django to create links but nginx to serve them.  This is explained in the django docs, not specific to django-admin-interface.

**Comment by nabinkhadka** [comment]
@merwok I am concerned why only logo has issue. Rest of the images work just fine.

**Comment by merwok** [comment]
My point was that there is no setup specific to the logo; if you have media files configured properly, logo should work too.  Without more info it’s hard to see what issue you have and where it comes from.

**Comment by fabiocaccamo** [comment]
@nabinkhadka this library doesn't work differently if you are working on development or production environment. 
If you need to manually add the initial `/` maybe your `MEDIA_URL` is not set correctly. 
As suggested by @merwok you should check your [media settings](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-MEDIA_URL).
