### ISSUE TITLE
Related Modal not closing

### ISSUE THREAD

**Issue by ArpanKIIT2017** [fabiocaccamo/django-admin-interface#91]
**Python version**
3.8.2

**Django version**
3.0.8

**Package version**
0.12.2

**Current behavior (bug description)**
Related Entry Modal not closing properly and not updating the master entry screen

**Expected behavior**
Related Entry Modal should close on save and update the master entry choice screen

**Comment by merwok** [comment]
Do you have any warnings or errors in the javascript console?

**Comment by fabiocaccamo** [comment]
Without error or warning info it is impossible to verify and debug the issue.

**Comment by fabiocaccamo** [comment]
@ArpanKIIT2017 any feedback?
