### ISSUE TITLE
Use conditional imports to avoid Django deprecation warnings

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#92]
force_text and ugettext* are deprecated, but they are needed for Python 2.

What do you think of going Python 3-only now that it’s 2020?
(It will always be possible to branch off an earlier version to make an important bugfix if needed.)

**Comment by fabiocaccamo** [comment]
@merwok I will support python 2 until it will be a limit to add new features or it will require too much effort to keep support it.
