### ISSUE TITLE
Move CSS/JS from inline HTML to own templates

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#93]
I’d like to move all the admin-interface CSS from the HTML template into a CSS template, so that the HTML pages only need `link rel=stylesheet`.  It would make the source shorter (good for view source!) and let the browser cache the stylesheet (using the appropriate cache headers based on a checksum or version, for invalidation).

_(from https://github.com/fabiocaccamo/django-admin-interface/issues/63#issuecomment-652528916)_

**Comment by fabiocaccamo** [comment]
Yes, this would be a great improvement. 
How do you plan to create the static files with dynamic css values?

**Comment by merwok** [comment]
They would be django views with templates, not static files :slightly_smiling_face:

**Comment by avanguardigit** [comment]
to get this result I on the base .html I called the tags on my custom class
`
{% load i18n static admin_interface_tags %}
{% get_admin_interface_theme as theme %}

<style>

        .grey-skin .navbar {
            color: {{ theme.css_header_text_color }};
            background-color: {{ theme.css_header_background_color }};
        }

        .grey-skin .navbar.double-nav a {
            color: {{ theme.title_color }};
        }

        .grey-skin .page-footer {
            color: {{ theme.css_header_text_color }};
            background-color: {{ theme.css_header_background_color }};
        }



        .grey-skin .navbar .navbar-nav .nav-item .dropdown-menu a:hover, .grey-skin .navbar .navbar-nav .nav-item .dropdown-menu a:focus, .grey-skin .navbar .navbar-nav .nav-item .dropdown-menu a:active .footer-copyright {
            color: {{ theme.css_header_text_color }};
            background-color: {{ theme.css_header_background_color }};
        }
        .grey-skin .btn-primary {
            background-color: {{ theme.css_save_button_background_color }}!important;
        }

        .grey-skin .btn-primary:not([disabled]):not(.disabled).active, .grey-skin .btn-primary:not([disabled]):not(.disabled):active, .show>.grey-skin .btn-primary.dropdown-toggle {
            background-color: {{ theme.css_save_button_background_hover_color }}!important;
            box-shadow: 0 5px 11px 0 rgba(0,0,0,.18), 0 4px 15px 0 rgba(0,0,0,.15);
        }

        .header_module_primary, .grey-skin .form-header, .grey-skin .card-header {
            color: {{ theme.css_module_text_color }};
            background-color: {{ theme.css_module_background_color }};
        }
`

**Comment by fabiocaccamo** [comment]
@merwok that would work and it is very easy to do, the only thing I don'like is that it would need one more configuration step because this package would have its own urls to be added to the main url conf. Have you any idea to avoid this?

**Comment by merwok** [comment]
🤔  what about…  admin extra views?  these can be defined in the base admin class and automatically used by subclasses 💪🏽

**Comment by fabiocaccamo** [comment]
@merwok good idea!

**Comment by fabiocaccamo** [comment]
@merwok do you think it is possible to use admin extra views without extending `django.contrib.admin.AdminSite` ?

**Comment by merwok** [comment]
Yes, the extra views are defined on Admin subclasses, not AdminSite.
This project could provide a mixin compatible with admin, and/or a ModelAdmin subclass to be used as base class in projects.

**Comment by fabiocaccamo** [comment]
Looking at PR #157 this issue will be solved at 95% without adding extra configuration.

**Comment by merwok** [comment]
Indeed, using CSS variables to let the browser do the templating in truly static files is a great solution!

**Comment by merwok** [comment]
Quite nice to see requests to CSS files with `304 Not Modified` responses 🙂 
The remaining style and links takes one screenful, that’s not too bad.
